/* Atlas of the Curious — dataset
   Every field is rendered via textContent only (no HTML interpolation).
   Coordinates are approximate and for travel inspiration. */
(function () {
  "use strict";

  // Accents document css/tokens.css and are validated against it; rendering
  // reads CSS tokens exclusively.
  var CATEGORIES = [
    { id: "geology", label: "Geology & Landforms", accent: "#e8b45a" },
    { id: "coastal", label: "Coastal & Marine", accent: "#4fc3f7" },
    { id: "desert", label: "Deserts & Dunes", accent: "#f0975a" },
    { id: "forest", label: "Forests & Jungles", accent: "#66bb6a" },
    { id: "glacier", label: "Glaciers & Ice", accent: "#90caf9" },
    { id: "sacred", label: "Sacred & Ancient", accent: "#ce93d8" },
    { id: "urban", label: "Urban Oddities", accent: "#ef5350" }
  ];

  var PLACES = [
    // ---------- Geology & Landforms ----------
    {
      id: "salar-de-uyuni",
      name: "Salar de Uyuni",
      nativeName: "Salar de Uyuni",
      nativeLang: "es",
      country: "Bolivia",
      region: "Altiplano, southwest Bolivia",
      category: "geology",
      symbol: "◇",
      tagline: "The world’s largest mirror, four kilometres above the sea.",
      story: "When a prehistoric lake drained millions of years ago it left the largest salt flat on Earth: 10,582 square kilometres of white, so perfectly flat that you cannot see the horizon in any direction. In the rainy season a few centimetres of rain turn the surface into a flawless mirror of sky and stars — the famous 'Sky Mirror' — so you can walk as if floating in space.",
      fact: "Roughly half of the world’s lithium reserves are locked in the brine beneath this flat, making it both a wonder and a quiet geopolitical prize.",
      coordinates: "19.917° S, 67.846° W",
      bestTime: "Rainy season (Dec–Mar) for the 'Sky Mirror'; dry season (Jun–Aug) for the flat",
      nearestCity: "Sucre or La Paz (≈ 260–400 km)"
    },
    {
      id: "pamukkale",
      name: "Pamukkale",
      nativeName: "Pamukkale",
      nativeLang: "tr",
      country: "Türkiye",
      region: "Denizli Province, southwestern Türkiye",
      category: "geology",
      symbol: "❄",
      tagline: "A mountain built floor by floor by hot springs.",
      story: "Mineral-rich spring water cascades down a hillside and hardens as it cools, laying down millimetre-thin sheets of travertine. Over millennia this built white terraces that look like frozen waterfalls — and the ancient city of Hierapolis, built on the rim around 190 BC, used the warm pools as a spa. Today you can walk the terraces and bathe in the ancient thermal pools beneath a marble theatre.",
      fact: "The terraces are a UNESCO World Heritage Site, and you walk them barefoot because shoes scuff the travertine that is still forming. The pool water holds around 35°C in winter.",
      coordinates: "37.921° N, 29.124° E",
      bestTime: "April–June and Sept–Oct, for warm water and mild light",
      nearestCity: "Denizli (≈ 18 km)"
    },
    {
      id: "wadi-rum",
      name: "Wadi Rum",
      nativeName: "وادي رم",
      nativeLang: "ar",
      country: "Jordan",
      region: "Southern Jordan, near the Saudi border",
      category: "geology",
      symbol: "↯",
      tagline: "The 'Valley of the Moon' that NASA used to rehearse for Mars.",
      story: "A vast desert of rust-red sand, black basalt, and towering sandstone towers, carved by wind and flash floods over millions of years. Bedouin tribes have called it home for centuries, and their rock art — over 20,000 inscriptions and carvings — covers the valley walls, from prehistoric gazelles to medieval poetry.",
      fact: "Because its geology resembles the Martian surface, Wadi Rum has served as a training and rehearsal site for space agencies and sci-fi film crews, including parts of 'The Martian'.",
      coordinates: "29.587° N, 35.429° E",
      bestTime: "Oct–Apr, when the desert is cool enough to walk at night",
      nearestCity: "Aqaba (≈ 60 km)"
    },
    {
      id: "marble-caves",
      name: "Marble Caves (Grottoes of General Carrera)",
      nativeName: "Capillas de Mármol",
      nativeLang: "es",
      country: "Chile",
      region: "Aysén Region, Lake General Carrera, Chile/Argentina border",
      category: "geology",
      symbol: "✦",
      tagline: "A cathedral of banded stone beneath turquoise water.",
      story: "On the Chilean shore of South America’s largest lake, freshwater waves have spent thousands of years dissolving and sculpting the marble into caverns. The water itself is the light source: turquoise light filters through the surface and plays across walls banded in green, blue, and white, making the whole cave look like a stained-glass window that slowly moves with the wind.",
      fact: "The caves’ colour shifts through the day with the sun’s angle; at dawn the walls glow pale blue, and by midday they turn deep emerald.",
      coordinates: "46.403° S, 72.800° W",
      bestTime: "Oct–Mar (Chilean summer), when light reaches deepest",
      nearestCity: "Puerto Natales (≈ 110 km)"
    },

    // ---------- Coastal & Marine ----------
    {
      id: "ha-long-bay",
      name: "Ha Long Bay",
      nativeName: "Vịnh Hạ Long",
      nativeLang: "vi",
      country: "Vietnam",
      region: "Quang Ninh Province, northern Vietnam",
      category: "coastal",
      symbol: "≈",
      tagline: "Nearly 2,000 limestone islands where the sea learned to float stone.",
      story: "Legend says a mother dragon descended to fight a sea monster and spat out strings of jewels that became these islands. Geology agrees with the outline: karst towers of ancient limestone, eroded into spires, arches, and caves, drowned when sea levels rose. You can kayak through hangings caves that are hundreds of metres deep and climb to the top of a tower for a view over an ocean of stone.",
      fact: "Ha Long Bay has been a UNESCO World Heritage Site since 1992. Around 50,000 people still live on floating villages in the bay.",
      coordinates: "20.910° N, 107.183° E",
      bestTime: "Oct–Dec and April, for calm seas and less haze",
      nearestCity: "Hanoi (≈ 170 km)"
    },
    {
      id: "komodo",
      name: "Komodo National Park",
      nativeName: "Taman Nasional Komodo",
      nativeLang: "id",
      country: "Indonesia",
      region: "Lesser Sunda Islands, between Bali and Sulawesi",
      category: "coastal",
      symbol: "◈",
      tagline: "A marine park that shares its beaches with the world’s largest living lizard.",
      story: "Komodo Island is the only home of the komodo dragon — a 3-metre predator that evolved here in near-isolation. But the park is bigger than the dragon: 2,400 square kilometres of coral reefs, white-sand beaches, and clear water, making it one of the top dive destinations on Earth. On Padar Island you can stand on a volcanic peak and look down on two crescent beaches at once.",
      fact: "The komodo dragon’s bite delivers a battery of venomous glands in its lower jaw — confirmed by a 2009 study — not just bacteria in its mouth, as once believed.",
      coordinates: "8.515° S, 119.451° E",
      bestTime: "Apr–Oct (dry season), when the water is calm and clear",
      nearestCity: "Labuan Bajo, Flores (the main gateway)"
    },
    {
      id: "dahab-blue-hole",
      name: "The Blue Hole, Dahab",
      nativeName: "البلو هول، دهب",
      nativeLang: "ar",
      country: "Egypt",
      region: "Gulf of Aqaba, Sinai Peninsula",
      category: "coastal",
      symbol: "◉",
      tagline: "A 100-metre-deep hole in the reef that glows sapphire from above.",
      story: "A natural sinkhole in the coral reef, 30 metres across and over 100 metres deep. From the surface it looks like a perfect blue eye; from underwater, a tunnel runs at 55 metres and opens into a vast cavern. It is one of the world’s most famous — and most feared — dive sites: the current and the depth make it lethal for the unprepared.",
      fact: "The Blue Hole was the site of the 1960s 'Blue Hole' expedition led by Jacques Cousteau, which established its depth and mapped its interior.",
      coordinates: "28.544° N, 34.555° E",
      bestTime: "May–Sept, when visibility is best and the water is warm",
      nearestCity: "Dahab (itself) / Sharm el-Sheikh (≈ 90 km)"
    },
    {
      id: "yucatan-cenotes",
      name: "Cenotes of the Yucatán",
      nativeName: "Cenotes de Yucatán",
      nativeLang: "es",
      country: "Mexico",
      region: "Yucatán Peninsula, Mexico",
      category: "coastal",
      symbol: "◍",
      tagline: "Thousands of open sinkholes where Maya ceremonies met the underworld.",
      story: "The Yucatán is a giant underwater cavern system of dissolved limestone. Where the ceilings collapsed, open shafts of clear, cold water formed: cenotes. Some are shallow and sunlit, some are dark caves you swim through with a single beam of light. The Maya believed cenotes were doors to Xibalba, the underworld, and some still hold ritual offerings, including gold and human remains.",
      fact: "There are an estimated 30,000+ cenotes on the peninsula, and they are the only water source for much of the region — the surface rivers simply sink into the ground.",
      coordinates: "20.500° N, 87.300° W",
      bestTime: "Nov–Mar (dry season), when the water is clearest",
      nearestCity: "Valladolid or Merida (≈ 20–100 km)"
    },

    // ---------- Deserts & Dunes ----------
    {
      id: "libyan-glass-desert",
      name: "The Libyan Glass Desert",
      nativeName: "صحراء الزجاج الليبي",
      nativeLang: "ar",
      country: "Libya",
      region: "Western Sahara, near the Egyptian border",
      category: "desert",
      symbol: "✧",
      tagline: "Dunes of natural glass, fused by a 29,000-year-old impact.",
      story: "About 29,000 years ago a meteorite struck this stretch of sand with enough energy to flash-melt the silica into glass. Wind and sand have since ground the glass into millions of translucent shards, so the dunes sparkle like crushed diamonds and will slice anything that crosses them barefoot. It is one of the few places on Earth where you can walk on a field of natural meteorite glass.",
      fact: "The glass, called 'Libyan desert glass', was already being used for flint-like cutting tools 30,000 years ago — among the earliest human use of meteorite material.",
      coordinates: "24.779° N, 21.223° E",
      bestTime: "Oct–Mar, when the desert is cool enough to cross",
      nearestCity: "Sebha (≈ 250 km)"
    },
    {
      id: "valley-of-the-moons",
      name: "Valley of the Moon",
      nativeName: "Mondlandschaft",
      nativeLang: "de",
      country: "Namibia",
      region: "Erongo Region, central Namibia",
      category: "desert",
      symbol: "☾",
      tagline: "Rusting iron towers in a desert that eats its own mountains.",
      story: "These 'moonstones' are boulders that rolled down the Brandberg massif, where iron in their cores oxidised into a rust-red crust. Over decades they 'melt' into their own bases as the wind and heat gnaw them, leaving a field of red monoliths that look weathered by time rather than wind. At dusk the whole valley glows like an ember field.",
      fact: "The nearby Brandberg shelters the 'Brandberg Paintings', rock art dating to roughly 6,000 years old — among the oldest in southern Africa.",
      coordinates: "21.951° S, 15.061° E",
      bestTime: "May–Oct, the cool dry season",
      nearestCity: "Swakopmund (≈ 80 km)"
    },
    {
      id: "erg-chebbi",
      name: "Erg Chebbi",
      nativeName: "عرق الشبي",
      nativeLang: "ar",
      country: "Morocco",
      region: "Drâa-Tafilalet Region, southeast Morocco",
      category: "desert",
      symbol: "☾",
      tagline: "The Sahara’s most famous dune sea — and a desert that sings at night.",
      story: "A chain of dunes stretching over 40 kilometres, with peaks up to 150 metres. The sand shifts colour with the sun — amber at dawn, rose at sunset, deep purple under the stars. On cold, still nights the dunes can 'sing': a low rumble produced when wind-blown sand grains, of a very specific size, cascade down the dune faces and vibrate against each other.",
      fact: "The 'singing dunes' phenomenon is studied by acousticians: only dunes with grains between roughly 0.1 and 0.5 mm in diameter produce the sound.",
      coordinates: "31.157° N, 3.972° W",
      bestTime: "Oct–May; nights are best to hear the 'singing dunes'",
      nearestCity: "Rissani (≈ 30 km)"
    },
    {
      id: "siwa-oasis",
      name: "Siwa Oasis",
      nativeName: "واحة سيوة",
      nativeLang: "ar",
      country: "Egypt",
      region: "Western Desert, near the Libyan border",
      category: "desert",
      symbol: "◉",
      tagline: "The oasis where Alexander the Great was told he was a god.",
      story: "A small oasis ringed by dunes and mountains, home to a community of over 20,000 people and to the ruins of the Temple of Amun. In 331 BC Alexander the Great came here to consult the oracle before his Egyptian campaign; the priests told him he was the son of Zeus, and he spent the rest of his life banking on it. The ancient temples, some with Ptolemaic and Roman reliefs, are still standing in the shade of date palms.",
      fact: "Siwa’s dates are famous in Egypt; the oasis also produces a natural, highly concentrated salt that was traded across the Sahara for centuries.",
      coordinates: "29.204° N, 25.518° E",
      bestTime: "Oct–Apr, when the desert is walkable",
      nearestCity: "Siwa (itself), reached via Dakhla or Matruh"
    },

    // ---------- Forests & Jungles ----------
    {
      id: "danum-valley",
      name: "Danum Valley",
      nativeName: "Lembah Danum",
      nativeLang: "ms",
      country: "Malaysia (Borneo)",
      region: "Sabah, Malaysian Borneo",
      category: "forest",
      symbol: "♠",
      tagline: "One of the last untouched blocks of lowland rainforest on Earth.",
      story: "4,500 hectares of continuous lowland rainforest that has barely been logged, ringed by mountain jungle. It holds pygmy elephants, orangutans, clouded leopards, and over 400 species of bird. The canopy walkway lets you walk 20 metres up in the treetops, where the forest sounds completely different: quieter, hotter, and full of life you can’t hear from the ground.",
      fact: "The Danum Valley Conservation Area was set aside in 1992 and has never been logged; it is one of the best-studied rainforest sites in Asia.",
      coordinates: "5.007° N, 117.830° E",
      bestTime: "Year-round (equatorial), though May–Oct is a touch drier",
      nearestCity: "Sandakan, Sabah (≈ 1 hour by boat)"
    },
    {
      id: "hoh-rainforest",
      name: "Hoh Rainforest",
      nativeName: "Hoh Rainforest",
      nativeLang: "en",
      country: "United States",
      region: "Olympic National Park, Washington State",
      category: "forest",
      symbol: "♣",
      tagline: "The 'Mistlands' — a temperate rainforest that drinks the sky.",
      story: "On the western coast of Washington, ocean fog rolls in from the Pacific and the forest literally drinks it. The Hoh rainforest is one of the largest temperate rainforests in the US: 3,000-year-old Sitka spruce, mossy arches, and a green so deep it has its own word, 'Mistlands'. It gets over 3 metres of precipitation a year, most of it as fog.",
      fact: "The Hoh River runs clear and cold even in winter because the forest’s dense canopy and cool soil keep it shaded; the water is one of the coldest freshwater systems on the US West Coast.",
      coordinates: "47.872° N, 124.013° W",
      bestTime: "Year-round; Jun–Sept is the driest, May the mistiest",
      nearestCity: "Port Angeles, WA (≈ 40 km)"
    },
    {
      id: "yasuni",
      name: "Yasuní",
      nativeName: "Parque Nacional Yasuní",
      nativeLang: "es",
      country: "Ecuador",
      region: "Amazon Basin, eastern Ecuador",
      category: "forest",
      symbol: "♦",
      tagline: "The most biodiverse hectare of forest on Earth.",
      story: "A corner of the eastern Amazon so rich in life that ecologists have called it the most biodiverse place on the planet: over 6,000 species of butterflies, 600+ bird species, and a single hectare of forest that can hold more tree species than an entire European country. The river itself is a highway for pink river dolphins, caimans, and the giant otter.",
      fact: "Yasuní is also home to at least four isolated indigenous groups who have had no outside contact — their territory is legally protected so they can remain so.",
      coordinates: "0.500° S, 75.300° W",
      bestTime: "Dry season (Dec–May), though it is a true rainforest year-round",
      nearestCity: "Puyo or Quito (≈ 200–350 km)"
    },
    {
      id: "baobab-avenue",
      name: "Avenue of the Baobabs",
      nativeName: "Allée des Baobabs",
      nativeLang: "fr",
      country: "Madagascar",
      region: "Mongoly, western Madagascar",
      category: "forest",
      symbol: "♠",
      tagline: "A row of 800-year-old bottle trees lining a dead riverbed.",
      story: "A stretch of road lined with giant baobabs, some over 800 years old and 20 metres tall, their trunks up to 9 metres in diameter. They line the bed of a river that no longer flows, and the trees have been here long enough that the local Antandroy people wove them into their origin myths. At sunset the silhouettes look like giants standing watch over a vanished river.",
      fact: "Baobabs store up to 120,000 litres of water in their trunks — enough to survive years of drought, and enough to water a village.",
      coordinates: "23.140° S, 43.500° E",
      bestTime: "May–Oct (dry season), for the clearest light and sunsets",
      nearestCity: "Morondava (≈ 35 km)"
    },

    // ---------- Glaciers & Ice ----------
    {
      id: "perito-moreno",
      name: "Perito Moreno Glacier",
      nativeName: "Glaciar Perito Moreno",
      nativeLang: "es",
      country: "Argentina",
      region: "Los Glaciares National Park, Patagonia",
      category: "glacier",
      symbol: "❄",
      tagline: "The only large glacier on Earth that still advances — and crashes.",
      story: "Most glaciers are retreating; Perito Moreno is one of the few that is roughly in balance, and every few years its lobe pushes out over Lago Argentino and dams the channel until the ice, 60 metres high above the waterline, collapses in a thunderous crash. The collapse can be seen from a viewing platform a few hundred metres away, and it sounds like the earth clearing its throat.",
      fact: "The glacier is about 30 kilometres long and 5 kilometres wide; the ice is up to 200 metres thick, and the blue you see is from the ice itself, not the sky.",
      coordinates: "50.493° S, 73.136° W",
      bestTime: "Dec–Mar (Patagonian summer) — calving is most dramatic then",
      nearestCity: "El Calafate (≈ 100 km)"
    },
    {
      id: "jokulsarlon",
      name: "Jökulsárlón",
      nativeName: "Jökulsárlón",
      nativeLang: "is",
      country: "Iceland",
      region: "Southeast Iceland, below Vatnajökull",
      category: "glacier",
      symbol: "◆",
      tagline: "A lagoon of drifting blue icebergs under a sky that never quite darkens in summer.",
      story: "Where the Vatnajökull glacier calves into the sea, Jökulsárlón collects icebergs that drift from deep blue to pure white before washing up on the nearby 'Diamond Beach', where they lie on black sand like jewels. The lagoon is so shallow in places that you can see the ice from above and below at once.",
      fact: "The lagoon was created in 1934 when a glacier dammed a river; it has since grown to over 18 square kilometres and is still expanding.",
      coordinates: "64.075° N, 16.236° W",
      bestTime: "Year-round; aurora Sep–Mar",
      nearestCity: "Vík (≈ 50 km) / Reykjavík (≈ 250 km)"
    },
    {
      id: "vatnajokull-blue-ice",
      name: "Vatnajökull Blue Ice Caves",
      nativeName: "Íshellar í Vatnajökli",
      nativeLang: "is",
      country: "Iceland",
      region: "Vatnajökull National Park, southeast Iceland",
      category: "glacier",
      symbol: "◈",
      tagline: "Caves that exist for only a few months each year, inside the largest glacier in Europe.",
      story: "Vatnajökull, the largest glacier in Europe by volume, forms natural caves every winter as meltwater carves tunnels into the ice. The ice is so dense and old that it scatters all colours of light except blue, which is why the caves glow a deep, almost impossible blue. Each year the caves shift, collapse, or form anew — the same cave rarely survives two seasons.",
      fact: "The ice in Vatnajökull is up to 9,000 years old at its core; the blue caves only form in the newer, more compressed surface layers.",
      coordinates: "64.400° N, 16.900° W",
      bestTime: "Mar–May, when the winter caves are safest",
      nearestCity: "Vík (≈ 50 km)"
    },
    {
      id: "baltoro-glacier",
      name: "Baltoro Glacier",
      nativeName: "بالتورو گلیشیئر",
      nativeLang: "ur",
      country: "Pakistan",
      region: "Gilgit-Baltistan, Karakoram range",
      category: "glacier",
      symbol: "❄",
      tagline: "The longest glacier outside the polar regions — 63 kilometres of moving ice.",
      story: "Baltoro is the longest glacier in the world outside Antarctica and Greenland, stretching 63 kilometres from the Karakoram peaks down to the Indus river. It is also the starting point for most expeditions to K2, the second-highest mountain on Earth, which rises 6,000 metres above the glacier’s surface. The glacier itself is a landscape of seracs, crevasses, and blue ice that changes shape with every season.",
      fact: "Baltoro was first surveyed in 1892 by the Austrian explorer Eduard von Schwanbaur, who was one of the first non-local Europeans to walk its full length.",
      coordinates: "35.800° N, 76.500° E",
      bestTime: "Jun–Sept, the trekking and climbing season",
      nearestCity: "Skardu (≈ 100 km)"
    },

    // ---------- Sacred & Ancient ----------
    {
      id: "angkor-wat",
      name: "Angkor Wat",
      nativeName: "អង្គរវត្ត",
      nativeLang: "km",
      country: "Cambodia",
      region: "Siem Reap, northwestern Cambodia",
      category: "sacred",
      symbol: "✺",
      tagline: "The largest religious monument on Earth, carved as a model of the Hindu cosmos.",
      story: "Built in the 12th century under King Suryavarman II, Angkor Wat is a model of the Hindu universe: five central towers represent the peaks of Mount Meru, a moat represents the cosmic ocean, and the bas-relief gallery inside holds 600 metres of carved narrative, including the most famous scene in Khmer art, the Churning of the Ocean of Milk. The temple was built to face west — unlike earlier Khmer temples — which has led some scholars to suggest it was also a funerary temple for the king himself.",
      fact: "Angkor Wat has never been fully looted; the reason is debated, but one theory is that the temple’s westward orientation made it too large and complex for the Khmer looting parties to ransack in a single season.",
      coordinates: "13.412° N, 103.867° E",
      bestTime: "Nov–Feb, the cool and least humid months",
      nearestCity: "Siem Reap (≈ 6 km)"
    },
    {
      id: "rapa-nui",
      name: "Rapa Nui (Easter Island)",
      nativeName: "Rapa Nui",
      nativeLang: "rap",
      country: "Chile",
      region: "Polynesia, eastern Pacific Ocean",
      category: "sacred",
      symbol: "◈",
      tagline: "A volcanic island in the middle of the Pacific, carved with 900 stone heads.",
      story: "Rapa Nui, about 3,500 km from South America and 2,000 km from the nearest inhabited island, is covered with moai: nearly 1,000 monolithic stone figures, most carved between 1250 and 1500 AD. The largest, on Rano Raraku volcano, is over 20 metres tall and weighs around 70 tonnes. The moai were carved from a single source of volcanic tuff, and the Rapa Nui people had no metal tools, no wheeled vehicles, and no draft animals — they moved them, somehow, up to 15 kilometres across the island.",
      fact: "The 2017 study by Terry Hunt and Carl Lipo suggested the moai were 'walked' upright using ropes in a rocking motion, rather than dragged on logs — a method that would explain the lack of tree stumps and soil disturbance at the moai sites.",
      coordinates: "27.112° S, 109.349° W",
      bestTime: "Nov–Mar (mild and dry); the island is remote",
      nearestCity: "Hanga Roa (itself); gateway is Santiago, Chile"
    },
    {
      id: "petra",
      name: "Petra",
      nativeName: "البتراء",
      nativeLang: "ar",
      country: "Jordan",
      region: "Ma'an Governorate, southern Jordan",
      category: "sacred",
      symbol: "✦",
      tagline: "A whole city carved out of rose-red sandstone, hidden for over 1,000 years.",
      story: "Petra was the capital of the Nabataean kingdom, a trading empire that controlled the incense routes between Arabia and the Mediterranean. The city is not built — it is carved, hundreds of tombs, temples, and public buildings cut into the face of sandstone cliffs. The most famous, the Treasury (Al-Khazneh), was carved from the top down, and for over a millennium after the city’s abandonment in the 6th century it was known only to local Bedouin, who kept its location secret from outsiders.",
      fact: "Petra’s water system, carved into the rock, could supply water to up to 30,000 people — a remarkable engineering feat for a city in the desert.",
      coordinates: "30.328° N, 35.444° E",
      bestTime: "Mar–May and Oct–Nov, for mild daytime heat",
      nearestCity: "Wadi Musa (≈ 25 km)"
    },
    {
      id: "tikal",
      name: "Tikal",
      nativeName: "Tikal",
      nativeLang: "es",
      country: "Guatemala",
      region: "Petén Basin, northern Guatemala",
      category: "sacred",
      symbol: "✺",
      tagline: "A Maya city of 300+ structures, half of which are still buried in the jungle.",
      story: "Tikal was one of the most powerful Maya cities for over a thousand years, at its peak home to perhaps 90,000 people. The six tallest pyramids still visible rise 70 metres above the jungle canopy, and the tallest, Temple IV, is the tallest structure built by the Maya. But the jungle has been closing over the site for centuries, and an estimated 300 structures are still buried under the trees, visible only from the air.",
      fact: "The Maya at Tikal played a form of ball game in a stadium that could hold thousands of spectators; the game may have had religious significance, and some players were sacrificed after important matches.",
      coordinates: "17.222° N, 89.623° W",
      bestTime: "Nov–Apr (dry season), when the canopy is clear",
      nearestCity: "Flores (≈ 90 km)"
    },

    // ---------- Urban Oddities ----------
    {
      id: "shibuya-crossing",
      name: "Shibuya Scramble Crossing",
      nativeName: "渋谷スクランブル交差点",
      nativeLang: "ja",
      country: "Japan",
      region: "Tokyo, Shibuya Ward",
      category: "urban",
      symbol: "⊕",
      tagline: "The busiest pedestrian crossing on Earth — 3,000 people at once, eight directions at once.",
      story: "Every 90 seconds the lights go green in all eight directions at once, and up to 3,000 people cross in a single wave. The crossing is a piece of urban choreography: no one looks at their phone, no one stops, and the flow is so smooth that it has become a landmark in its own right, appearing in countless films and documentaries. The giant screen above the crossing has been running since 1978.",
      fact: "The Shibuya Scramble was designed in 1962 and has been expanded several times; it now handles around 1,000 people per crossing cycle, and is one of the most-photographed urban spaces in the world.",
      coordinates: "35.659° N, 139.700° E",
      bestTime: "Year-round; cherry-blossom season (late Mar–Apr) for the best light",
      nearestCity: "Itself (Tokyo, in Shibuya)"
    },
    {
      id: "thimphu",
      name: "Thimphu",
      nativeName: "ཐིམ་ཕུག",
      nativeLang: "dz",
      country: "Bhutan",
      region: "Thimphu Valley, central Bhutan",
      category: "urban",
      symbol: "⊕",
      tagline: "A capital city with no traffic lights — and a rule that says you must smile.",
      story: "Thimphu, the capital of Bhutan, is one of the few cities in the world that has no traffic lights. Instead, a single traffic warden at the main junction directs cars, and the city’s compact size and gentle traffic make it workable. Bhutan also has a national dress code for men (the ghō) and women (the kira), and a 'Gross National Happiness' index that replaced GDP as the country’s primary measure of progress in the 1970s.",
      fact: "Thimphu is the only capital city in the world with no traffic lights; the city also bans plastic bags and charges for cigarette packs to discourage smoking.",
      coordinates: "27.471° N, 89.626° E",
      bestTime: "Mar–May and Sep–Nov, for the driest, clearest weather",
      nearestCity: "Itself (Bhutan's capital); Paro is the nearest airport"
    },
    {
      id: "potosi",
      name: "Potosí",
      nativeName: "Potosí",
      nativeLang: "es",
      country: "Bolivia",
      region: "Cerro Rico, southern Bolivia",
      category: "urban",
      symbol: "⊕",
      tagline: "A city built on top of a mountain of silver — and the mountain is still being mined.",
      story: "Potosí grew so fast in the 16th century, after Spanish colonists found Cerro Rico (the 'Rich Hill'), that it became the largest city in the Americas. The silver mined here paid for the Spanish Empire’s wars for over a century. The mountain is now nearly hollow, its surface riddled with thousands of mine entrances, and it is still being worked today. The city sits at 4,090 metres, the highest major city in the world, and the air is so thin that visitors often feel the altitude within an hour.",
      fact: "Cerro Rico is so hollowed out that it is slowly collapsing; engineers have estimated it has 100–200 years of structural stability left at current mining rates.",
      coordinates: "19.593° S, 65.726° W",
      bestTime: "Jun–Aug (cooler and dry), when the altitude is most bearable",
      nearestCity: "Itself (the highest large city in the world)"
    },
    {
      id: "fez-medina",
      name: "The Medina of Fez",
      nativeName: "فاس",
      nativeLang: "ar",
      country: "Morocco",
      region: "Fez, northwestern Morocco",
      category: "urban",
      symbol: "⊕",
      tagline: "A 900-year-old maze of 9,000 streets, with no cars, no roads, and no map that works.",
      story: "The Fez el-Bali medina is the largest car-free urban area in the world, and the oldest continuously inhabited city in Morocco. It has been expanding organically for over 900 years, with streets narrowing and doubling back until they form a maze that no single person can fully navigate. The medina is home to the Al-Qarawiyyin mosque, founded in 859, which is the oldest continuously operating university in the world. Getting lost is not a failure here — it is the point.",
      fact: "The Al-Qarawiyyin mosque and madrasa, founded by Fatima al-Fihri in 859, is recognised by UNESCO as the oldest surviving institution of higher learning in the world.",
      coordinates: "34.061° N, -4.979° E",
      bestTime: "March–May and September–October, when the desert heat and cold are both avoided",
      nearestCity: "Itself (Fez, one of Morocco's four imperial cities)"
    },

    // ---------- Added wonders (geographic spread) ----------
    {
      id: "zhangjiajie",
      name: "Zhangjiajie National Forest Park",
      nativeName: "张家界国家森林公园",
      nativeLang: "zh-Hans",
      country: "China",
      region: "Hunan Province, central China",
      category: "geology",
      symbol: "❖",
      tagline: "Nearly 3,000 quartzite pillars rising out of the forest like a city of stone spires.",
      story: "Wind and water have spent hundreds of millions of years sculpting the Wulingyuan mountains into thousands of steep quartzite pillars, some more than 300 metres tall. The pillars are so vertical and isolated that, when the cloud lifts off the valley floor, they read as a city of stone spires floating in the sky — the landscape that directly inspired the floating islands in the film 'Avatar'. The world's tallest glass-floor elevators and a walkway suspended over the faces of the columns let you travel hundreds of metres up the rock.",
      fact: "The pillar field is one of the best-preserved examples of a 'pillar karst' landscape on land, and the Wulingyuan area it sits in has been a UNESCO World Heritage Site since 1992.",
      coordinates: "29.324° N, 110.433° E",
      bestTime: "October–November, when the haze is clearest and the leaves are turning",
      nearestCity: "Zhangjiajie (≈ 50 km)"
    },
    {
      id: "kilimanjaro",
      name: "Mount Kilimanjaro",
      nativeName: "Mlima Kilimanjaro",
      nativeLang: "sw",
      country: "Tanzania",
      region: "Kilimanjaro Region, northern Tanzania",
      category: "geology",
      symbol: "⛰",
      tagline: "A free-standing volcano that climbs from savanna to a permanent ice cap.",
      story: "Kilimanjaro, at 5,895 metres, is the highest mountain in Africa and one of the largest free-standing volcanoes on Earth. Because it rises so abruptly from the surrounding plains, a single climb passes through equatorial savanna, cloud forest, alpine desert, and — at the summit — a permanent ice cap. The peak, Uhuru Peak, is high enough that its ice is being lost faster than it is replaced, and the glaciers have already shrunk to a fraction of their early-1900s extent.",
      fact: "Kilimanjaro is a dormant stratovolcano; its glaciers are a UNESCO World Heritage Site and are projected to disappear within a few decades at current rates of loss.",
      coordinates: "3.067° S, 37.355° E",
      bestTime: "January–March and June–October, the dry-season climbing windows",
      nearestCity: "Moshi (≈ 30 km)"
    },
    {
      id: "milford-sound",
      name: "Milford Sound",
      nativeName: "Piopiotahi",
      nativeLang: "mi",
      country: "New Zealand",
      region: "Fiordland, South Island",
      category: "coastal",
      symbol: "≋",
      tagline: "A drowned valley where the mountains fall straight into the sea.",
      story: "Milford Sound is one of the 'fiords' of southwestern New Zealand: a deep, narrow inlet carved by glaciers and then flooded as sea levels rose after the last ice age. The result is a body of water ringed by 1,200-metre cliffs that sheer straight into a dark green sea, with waterfalls plunging from the ridgelines and seals hauling out on the black beaches. On a still, rainy morning the mist hanging in the fiord gives it an almost prehistoric, green-and-black atmosphere.",
      fact: "Milford Sound is the single most-visited natural site in New Zealand; the fiord is over 5 km long, and a heavy rainstorm can add several metres of depth as the rivers feed it.",
      coordinates: "44.661° S, 167.932° E",
      bestTime: "Year-round, but November–March for the clearest, driest weather",
      nearestCity: "Te Anau (≈ 95 km)"
    },
    {
      id: "lofoten",
      name: "Lofoten Islands",
      nativeName: "Lofoten",
      nativeLang: "no",
      country: "Norway",
      region: "Lofoten, Nordland County, northern Norway",
      category: "coastal",
      symbol: "≋",
      tagline: "A jagged archipelago where the sea, the peaks, and the aurora share the same frame.",
      story: "The Lofoten archipelago is a chain of low, steep islands that climb out of the warm Gulf Stream waters near 68° north — far enough north for the midnight sun and the northern lights, but mild enough to hold reindeer and fishing villages. The 'fjeld' peaks rise almost vertically from the water, and the traditional red fishing cabins, or rorbu, sit on little piers over the deep sea. In winter the aurora borealis lights up the same sky as the peaks.",
      fact: "The name Lofoten literally means 'the place of the herring'; the warm North Atlantic Current keeps the waters ice-free, which is why the islands are far milder than other places at the same latitude.",
      coordinates: "68.150° N, 13.604° E",
      bestTime: "September–March for the northern lights; June for the midnight sun",
      nearestCity: "Å (≈ 20 km) / Svolvær (≈ 45 km)"
    },
    {
      id: "sossusvase",
      name: "Sossusvlei and Deadvlei",
      nativeName: "Sossusvlei en Dooievlei",
      nativeLang: "af",
      country: "Namibia",
      region: "Namib-Naukluft National Park, Namib Desert",
      category: "desert",
      symbol: "◑",
      tagline: "The tallest dunes on Earth, beside a salt pan of ancient dead trees.",
      story: "Sossusvlei is a basin at the foot of some of the tallest sand dunes in the world, several of them over 300 metres high and a vivid, iron-rich orange that deepens at sunset. Nearby, Deadvlei is a clay pan that was, about 900 years ago, ringed by a forest of camel-thorn trees; when the dunes blocked the river that fed them, the trees died but did not decay in the dry air, leaving a field of blackened, branchless trunks standing against a deep-orange dune backdrop.",
      fact: "Deadvlei's 'dead' trees have stood upright for hundreds of years because the dry, sealed environment stops them rotting; the dunes here among the highest on the planet.",
      coordinates: "24.733° S, 15.343° E",
      bestTime: "April–May and September–October, when it is warm enough to hike and the air is clear",
      nearestCity: "Walvis Bay (≈ 45 km, by 4×4)"
    },
    {
      id: "atacama",
      name: "The Atacama Desert",
      nativeName: "Desierto de Atacama",
      nativeLang: "es",
      country: "Chile",
      region: "Antofagasta / Calama, northern Chile",
      category: "desert",
      symbol: "☄",
      tagline: "The driest non-polar place on Earth — and a window onto the sky.",
      story: "The Atacama is the world's driest desert: some weather stations have never recorded rain, and the salt flats and hyper-arid valleys hold some of the oldest, most stable soils on Earth. Because the air is so dry and the region so dark and high, it is also one of the finest places on the planet to look up: the great professional observatories sit on its high plateaus, and the clear nights make it a natural dark-sky sanctuary.",
      fact: "Parts of the Atacama are so dry that NASA has used them to test and build Mars-landing hardware, because the chemistry and climate best resemble the Martian surface.",
      coordinates: "23.860° S, 69.130° W",
      bestTime: "April–November (the dry season); clear nights year-round for stargazing",
      nearestCity: "Calama (≈ 60 km)"
    },
    {
      id: "bialowieza",
      name: "Białowieża Forest",
      nativeName: "Puszcza Białowieska",
      nativeLang: "pl",
      country: "Poland / Belarus",
      region: "southeastern Poland and northeastern Belarus",
      category: "forest",
      symbol: "♣",
      tagline: "One of the last primeval lowland forests left in all of Europe.",
      story: "Białowieża is a huge block of forest that has been left largely untouched since the 19th century, and is the only place in Europe where the Eurasian bison still roam wild. The forest is also one of the few last pieces of primeval temperate forest on the continent: ancient oaks and lindens, some over 500 years old, stand in a web of moss, fungi, and deadwood that has been undisturbed for thousands of years. It was among the first sites in the world to be placed under international protection.",
      fact: "The forest's primeval stands are a UNESCO World Heritage Site; it is home to the last wild European bison and to one of the largest colonies of white storks in Europe.",
      coordinates: "52.750° N, 23.850° E",
      bestTime: "May–June and September, when the light is warm and the animals are most active",
      nearestCity: "Białystok (≈ 100 km)"
    },
    {
      id: "kakadu",
      name: "Kakadu National Park",
      nativeName: "Kakadu National Park",
      nativeLang: "en",
      country: "Australia",
      region: "Northern Territory, Australia",
      category: "forest",
      symbol: "♦",
      tagline: "A landscape where the rock art, the wetlands, and the billabongs have coexisted for 65,000 years.",
      story: "Kakadu is one of the wettest and oldest landscapes on Earth, a mix of savanna, wetlands, and escarpments where waterfalls and billabongs flood and dry with the seasons. Its rock shelters hold thousands of painted and stencilled images made by the Bininj/Mungguy people over tens of thousands of years — among the longest continuous records of human culture anywhere. In the wet season the park is a vast, flooded bird haven; in the dry it is a network of clear waterholes and sandstone escarpments.",
      fact: "Kakadu's rock art includes the distinctive 'X-ray' painting style and some of the oldest known depictions of now-extinct animals; the park is a UNESCO World Heritage Site.",
      coordinates: "12.833° S, 132.375° E",
      bestTime: "May–October (the dry season), when tracks are passable and the waterfalls still run",
      nearestCity: "Katherine (≈ 160 km) / Darwin (≈ 300 km)"
    },
    {
      id: "aletsch",
      name: "Aletsch Glacier",
      nativeName: "Aletschgletscher",
      nativeLang: "de",
      country: "Switzerland",
      region: "Valais, the Swiss Alps",
      category: "glacier",
      symbol: "❄",
      tagline: "The longest and thickest glacier in the Alps — a blue river of ice.",
      story: "The Aletsch Glacier drains the highest peaks of the Swiss Alps — the Matterhorn, the Mönch, and the Dufourspitze — into a single, 23-kilometre tongue of ice, the largest glacier in Europe outside the polar regions. From the high viewing points and the cable-car stations above it, the glacier reads as a slow river of blue ice, its surface crevassed and banded with layers of debris that mark each winter's snowfall. Like most Alpine glaciers it has been retreating for over a century, but it is still the dominant ice body in the range.",
      fact: "The Aletsch is up to 900 metres thick at its centre and has been measured since 1893; it feeds the Rhône River and is one of the classic high-Alpine trekking routes.",
      coordinates: "46.550° N, 8.050° E",
      bestTime: "July–September for trekking; winter for the snow and the ski area",
      nearestCity: "Zermatt (≈ 15 km)"
    },
    {
      id: "sigiriya",
      name: "Sigiriya Rock Fortress",
      nativeName: "සීගිරිය",
      nativeLang: "si",
      country: "Sri Lanka",
      region: "North Central Province, Sri Lanka",
      category: "sacred",
      symbol: "✺",
      tagline: "A palace built on a 200-metre column of rock, half ruin, half legend.",
      story: "In the 5th century the king Kassapa built Sigiriya as a fortress-and-palace on top of a sheer 180-metre column of rock, and today it is one of the best-preserved monuments of the ancient world. The climb up is itself a set piece: a series of moats and gardens, the famous 'lion gate' where the visitor grips a pair of massive carved paws to pass beneath a crouched lion, and the painted frescoes of 'the fair maidens' along the cliff face. The summit is a level terrace where the palace once stood, now open to the sky.",
      fact: "The frescoes of Sigiriya, dating from around the 5th century, are among the earliest and best-preserved examples of secular courtly painting in the Indian Ocean world; the site is a UNESCO World Heritage Site.",
      coordinates: "7.955° N, 80.760° E",
      bestTime: "November–March, the dry season, for clear views and a cooler climb",
      nearestCity: "Dambulla (≈ 5 km) / Anuradhapura (≈ 40 km)"
    },
    {
      id: "borobudur",
      name: "Borobudur",
      nativeName: "Candi Borobudur",
      nativeLang: "id",
      country: "Indonesia",
      region: "Central Java, Indonesia",
      category: "sacred",
      symbol: "✦",
      tagline: "The world's largest Buddhist monument, built as a three-dimensional map of the cosmos.",
      story: "Borobudur was raised in the 9th century as a stepped monument in the shape of a Buddhist cosmology: a lower base of stacked reliefs depicting the world of desire, a middle ring of square terraces covered in over 2,600 carved panels, and an upper dome of round terraces with 72 small stupas, each holding a Buddha. Climbing it is a slow journey from the earthward lower levels to the serene, open top, with the volcanic hills of Java spread out below. For many centuries it was buried under ash and jungle until it was rediscovered in the 19th century.",
      fact: "Borobudur is the largest Buddhist monument in the world; its reliefs include around 1,460 panels and 504 Buddha statues, and it is a UNESCO World Heritage Site.",
      coordinates: "7.608° S, 110.218° E",
      bestTime: "April–October (the dry season); dawn, when the first light hits the terraces",
      nearestCity: "Yogyakarta (≈ 40 km)"
    },
    {
      id: "istanbul",
      name: "Istanbul",
      nativeName: "İstanbul",
      nativeLang: "tr",
      country: "Türkiye",
      region: "spanning Europe and Asia, at the Bosphorus",
      category: "urban",
      symbol: "⊕",
      tagline: "The only city that is, literally, in two continents at once.",
      story: "Istanbul straddles the Bosphorus, the narrow strait that separates Europe from Asia, which makes it the only major city on two continents. It was, in turn, Byzantium, Constantinople, and the capital of the Ottoman Empire, and it stacks those layers in a single walk: Roman walls and the Hagia Sophia from the 6th century, Ottoman mosques with cascading domes, and a working bazaar where merchants have traded since the 15th century. The Bosphorus ferries that carry passengers between the two continents run every few minutes.",
      fact: "Istanbul's Grand Bazaar, with over 4,000 shops, and the nearby Spice Bazaar are among the oldest and largest covered markets in the world; the city was the capital of three successive empires.",
      coordinates: "41.008° N, 28.978° E",
      bestTime: "April–May and September–October, when the weather is mild and the light is good",
      nearestCity: "Itself (the largest city in Türkiye, population ≈ 16 million)"
    }
  ];

  window.ATLAS_DATA = Object.freeze({
    categories: CATEGORIES,
    places: PLACES
  });
})();
