/* Text Atlas — a full-screen, country-colored character-grid world map with
   a living, ripple-driven text sea. Sized to fill the viewport; rebuilt on
   resize. Data comes from js/landmap.js (generated by scripts/build-map.mjs
   from Natural Earth 110m country polygons):
     - Land: per-cell palette color (country hue × dither step) + texture glyph
     - Sea:  spring simulation over water cells; stirred by pointer move/tap,
       marker hovers, and ambient pulses; rendered as reactive glyphs.
     - Markers: colored dots with a coastline-routed name label; hover/focus/tap
       shows a pretext-wrapped hover card and lights the matching grid card.
     - Labels: place names routed into free sea cells around each dot, plus
       ocean and sea names set in spaced capitals (see "Labels on the map").
   CSP-safe: same-origin module import, no eval, textContent for all data. */
import {
  prepareWithSegments,
  layoutWithLines,
  measureLineStats,
  measureNaturalWidth
} from "../vendor/pretext/layout.js";
import { readFontRoles, directionFromLevels, dirForLang } from "./text.js";
import { routeText } from "./text-route.js";

(function () {
  "use strict";

  const DATA = window.ATLAS_DATA || { categories: [], places: [] };
  const MAPS = window.LANDMAPS;
  const catById = new Map(DATA.categories.map((c) => [c.id, c]));
  const $ = (id) => document.getElementById(id);

  const section = $("text-atlas");
  const viewport = section && section.querySelector(".map-viewport");
  if (!section || !viewport || !DATA.places.length) return;

  const isMobile = (typeof window.matchMedia === "function") &&
    window.matchMedia("(max-width: 640px)").matches;
  const PALETTE = (MAPS && MAPS.palette) || null;
  const MAP = (MAPS && (isMobile ? MAPS.mobile : MAPS.desktop)) || null;
  if (!MAP || !PALETTE || !MAP.glyphs || !MAP.glyphs.length) return;

  const COLS = MAP.cols;
  const ROWS = MAP.rows;

  // The map's monospace stack lives in css/style.css as --font-mono, so the
  // CSS the browser paints and the canvas font string pretext measures with
  // cannot drift. Named faces only: a generic keyword such as `ui-monospace`
  // can resolve to a different face in a canvas 2D context than in CSS, which
  // would put the character grid and its measurements out of step.
  const MONO_FALLBACK =
    'SFMono-Regular, Menlo, Consolas, "DejaVu Sans Mono", "Liberation Mono", monospace';
  const MONO = (function () {
    try {
      const v = getComputedStyle(document.documentElement)
        .getPropertyValue("--font-mono").trim();
      return v || MONO_FALLBACK;
    } catch (e) { return MONO_FALLBACK; }
  })();
  const DPR = Math.min(2, (typeof devicePixelRatio === "number" ? devicePixelRatio : 1) || 1);
  const ROW_FACTOR = 1.18;
  const PX_MAX = 18;
  // Mobile floor is low so the whole grid fits the content width — at 8px a
  // 96-col grid would be ~770px and get clipped on a phone.
  const PX_MIN = isMobile ? 4 : 8;
  // SPRING/DAMP/SPREAD/LIFT tune the interactive ripple field. SPREAD how fast
  // a splash's ring travels outward, DAMP how long it lasts (lower = longer),
  // LIFT how far crests visually bob the glyphs.
  const SPRING = 0.022, DAMP = 0.94, SPREAD = 0.22, LIFT = 5;

  // Wave-like ocean: three superposed traveling wave trains (a long eastward
  // swell, a slow westward set, and a fast short chop) with per-region front
  // tilt, rendered through a glyph + luminance ramp. Wave crests are
  // gamma-sharpened so they read as thin bright lines moving across the water
  // instead of a static smoke texture; the ripple spring on top carries
  // pointer splashes.
  const OCEAN_GLYPHS = ["·", "·", ":", "~", "≈", "≈"];
  const OCEAN_COLORS = [
    "rgba(74, 124, 164, 0.10)",
    "rgba(90, 146, 186, 0.17)",
    "rgba(110, 172, 208, 0.26)",
    "rgba(140, 200, 232, 0.38)",
    "rgba(176, 226, 248, 0.52)",
    "rgba(214, 244, 255, 0.70)"
  ];
  const WAVE_GAMMA = 1.9;          // >1 → quiet floor, thin bright crests
  // Clouds are withheld from Antarctica (it is already white ice): the fade
  // ramps 1 → 0 over the last few rows so a cloud dissolves into the ice.
  function cloudFade(row) {
    const startRow = ROWS - 5;
    if (row < startRow) return 1;
    return Math.max(0, 1 - (row - startRow) / 4);
  }
  const REDUCED = (typeof matchMedia === "function") &&
    matchMedia("(prefers-reduced-motion: reduce)").matches;

  // Monospace advance per px of font size (measured from the font engine).
  const _p = document.createElement("canvas").getContext("2d");
  _p.font = "100px " + MONO;
  const UNIT = _p.measureText("MMMMMMMMMM").width / 10 / 100;

  // Reflow-free wrapping via pretext (monospace grid ⇒ chars = cells).
  function wrapLines(text, font, maxCharsPx, maxChars, lineHeight) {
    text = String(text).trim();
    if (maxChars <= 0) return [text];
    if (text.length <= maxChars) return [text];
    try {
      const pre = prepareWithSegments(text, font);
      const res = layoutWithLines(pre, maxChars * maxCharsPx, lineHeight);
      if (res && res.lines && res.lines.length) {
        return res.lines.map((l) => l.text).filter((t) => t.length);
      }
    } catch (e) { /* fall back below */ }
    const words = text.split(/\s+/);
    const lines = [];
    let cur = "";
    for (const w of words) {
      if (!cur) cur = w;
      else if ((cur + " " + w).length <= maxChars) cur += " " + w;
      else { lines.push(cur); cur = w; }
    }
    if (cur) lines.push(cur);
    return lines;
  }

  function parseCoords(s) {
    const m = /(-?\d+(?:\.\d+)?)\s*°?\s*([NSns])[\s,]+(-?\d+(?:\.\d+)?)\s*°?\s*([EWew])/.exec(s || "");
    if (!m) return null;
    return { lat: m[1] * (m[2].toUpperCase() === "S" ? -1 : 1), lon: m[3] * (m[4].toUpperCase() === "W" ? -1 : 1) };
  }
  function project(p, cols, rows, charW, lineH) {
    const c = parseCoords(p.coordinates);
    if (!c) return null;
    const col = Math.max(0, Math.min(cols - 1, Math.round(((c.lon + 180) / 360) * cols)));
    const row = Math.max(0, Math.min(rows - 1, Math.round(((90 - c.lat) / 180) * rows)));
    return { col, row, x: (col + 0.5) * charW, y: (row + 0.5) * lineH };
  }
  // Great-circle distance (km) between two lat/lon pairs.
  function distKm(a, b) {
    const R = 6371, rad = Math.PI / 180;
    const dLat = (b.lat - a.lat) * rad, dLon = (b.lon - a.lon) * rad;
    const s = Math.sin(dLat / 2) ** 2 + Math.cos(a.lat * rad) * Math.cos(b.lat * rad) * Math.sin(dLon / 2) ** 2;
    return 2 * R * Math.asin(Math.min(1, Math.sqrt(s)));
  }
  const fmtKm = (km) => km < 1000 ? Math.round(km) + " km" : (km / 1000).toFixed(1) + "k km";

  // Cell kind: 0 = water, 1 = land (color = palette index).
  const kind = new Uint8Array(COLS * ROWS);
  const cellColor = new Uint8Array(COLS * ROWS);
  const cellGlyph = new Uint8Array(COLS * ROWS);
  for (let r = 0; r < ROWS; r++) {
    const gRow = MAP.glyphs[r], cRow = MAP.colors[r];
    for (let c = 0; c < COLS; c++) {
      const i = r * COLS + c;
      if (cRow[c] !== " ") {
        kind[i] = 1;
        cellColor[i] = cRow.charCodeAt(c) - 65; // 'A' → 0
        cellGlyph[i] = gRow.charCodeAt(c);
      }
    }
  }

  // Neighbour lists for the water-cell spring simulation.
  const neighbors = new Int32Array(COLS * ROWS * 4);
  const nCount = new Uint8Array(COLS * ROWS);
  for (let r = 0; r < ROWS; r++) {
    for (let c = 0; c < COLS; c++) {
      const i = r * COLS + c;
      if (kind[i]) continue;
      let n = 0;
      if (c > 0 && !kind[i - 1]) neighbors[i * 4 + n++] = i - 1;
      if (c < COLS - 1 && !kind[i + 1]) neighbors[i * 4 + n++] = i + 1;
      if (r > 0 && !kind[i - COLS]) neighbors[i * 4 + n++] = i - COLS;
      if (r < ROWS - 1 && !kind[i + COLS]) neighbors[i * 4 + n++] = i + COLS;
      nCount[i] = n;
    }
  }
  const waterCells = [];
  for (let i = 0; i < COLS * ROWS; i++) if (!kind[i]) waterCells.push(i);

  const places = DATA.places
    .map((p) => ({ p, accent: (catById.get(p.category) || {}).accent || "#e8b45a" }))
    .filter((x) => parseCoords(x.p.coordinates));

  /* ==================================================================== *
   * Labels on the map                                                     *
   * ==================================================================== *
   *
   * Every label — a place name, a place tagline, an ocean name — is text
   * poured into *free water cells* of the same character grid the map is drawn
   * on. Three ideas hold it together:
   *
   * 1. Two masks. `kind` (built above, never changes) says which cells are
   *    land. `occupancy` is rebuilt from scratch on every placement and says
   *    which cells this frame's labels have already claimed. A cell is free
   *    when it is water and unclaimed.
   *
   * 2. Screen px, not map px. Labels counter-scale with 1/--zoom exactly like
   *    the markers, so a label keeps a constant on-screen size at any zoom.
   *    A grid cell, on the other hand, grows with the zoom: on screen it is
   *    CHARW * zoom wide. So zooming in buys the label more cells for the same
   *    number of characters — which is the whole reason the zoom tiers below
   *    can afford to show more text the closer you get.
   *
   * 3. One line per grid row. Each label line is laid out at the width of its
   *    own row's free run and painted with a line box exactly one grid row
   *    tall, so what was routed and what is painted occupy the same cells.
   *    ATLAS_MAP_DEBUG.checkLabels() re-derives those cells from the rendered
   *    geometry and walks them against the land mask, which is what makes
   *    "no label overlaps land or another label" a testable claim.
   *
   * Preparation (the expensive pretext pass) happens once per string; a zoom
   * change only re-runs routing, never `prepareWithSegments()`. */

  // Feature flags. js/text.js owns DEFAULT_FLAGS and this phase must not edit
  // it, so the defaults for the three Phase 1 flags live here, read with
  // "on unless explicitly false" semantics. `?flags=` / `?noflags=` still work:
  // js/text.js has already merged the query string into window.ATLAS_FLAGS by
  // the time this module runs (both are deferred, so document order holds).
  const FLAGS = (window.ATLAS_FLAGS = window.ATLAS_FLAGS || {});
  FLAGS.labels = FLAGS.labels !== false;
  FLAGS.oceanLabels = FLAGS.oceanLabels !== false;
  FLAGS.hoverFit = FLAGS.hoverFit !== false;
  FLAGS.nativeNames = FLAGS.nativeNames !== false;

  // Font roles, resolved straight out of the CSS registry so the canvas font
  // pretext measures with is the font the browser paints (see js/text.js).
  const ROLES = (function () {
    try {
      return readFontRoles(document, [
        "map-label", "ocean-label", "hover-card", "map-label-native", "native-name"
      ]);
    } catch (e) { return {}; }
  })();
  const ROLE_LABEL = ROLES["map-label"] || null;
  const ROLE_OCEAN = ROLES["ocean-label"] || null;
  const ROLE_TAG = ROLES["hover-card"] || null;
  const ROLE_NATIVE = ROLES["map-label-native"] || null;
  function fontPxOf(role) {
    const m = role && /(\d*\.?\d+)px/.exec(role.font);
    return m ? parseFloat(m[1]) : 0;
  }

  // Labels are a desktop affordance: below 640px the hover card carries the
  // name and the grid is far too small to route into.
  const LABELS_ON = !isMobile && FLAGS.labels && !!ROLE_LABEL;
  const OCEAN_ON = !isMobile && FLAGS.oceanLabels && !!ROLE_OCEAN;

  // Zoom tiers. Below NAME the map is a picture, not a gazetteer; from NAME
  // each dot gets its name; from TAG the name is joined by its tagline.
  const TIER_NAME_Z = 1.4;
  const TIER_TAG_Z = 2.4;
  const NAME_MAX_LINES = 3;
  const TAG_MAX_LINES = 3;
  // The native name sits between the two. Two rows is plenty for every name in
  // the dataset; a name that will not fit in them is simply left off this
  // label rather than pushing the tagline out of the water.
  const NATIVE_MAX_LINES = 2;
  // How far from the dot an anchor may sit, in cells. Nothing in the dataset
  // is further than 3 cells from water on the 150×39 grid (deserts and inland
  // forests are the far ones), so 4 covers every marker.
  const LABEL_MAX_OFFSET = 4;
  const LABEL_RUN_LIMIT = 44;       // longest free run worth scanning, in cells
  const MARKER_PX = 19;             // .map-marker { width: 19px } — kept clear
  const ZOOM_STEP = 0.05;           // re-place once the zoom moves this much

  // Ocean and sea names. Anchors are the point the name wants to be centred
  // on; placement slides left/right along the row to find a free run, and any
  // name that cannot find one at the current zoom is simply not drawn — the
  // Mediterranean, for instance, is barely five cells of water on this grid,
  // so it only appears once the zoom has made those five cells wide enough.
  const OCEANS = [
    { name: "Pacific Ocean", lat: 0, lon: -132 },
    { name: "Pacific Ocean", lat: 2, lon: 172 },
    { name: "Atlantic Ocean", lat: 33, lon: -42 },
    { name: "Atlantic Ocean", lat: -28, lon: -18 },
    { name: "Indian Ocean", lat: -22, lon: 78 },
    { name: "Southern Ocean", lat: -60, lon: 26 },
    { name: "Arctic Ocean", lat: 84, lon: 10 },
    { name: "Mediterranean", lat: 37, lon: 15 },
    { name: "Caribbean Sea", lat: 15, lon: -74 },
    { name: "Arabian Sea", lat: 15, lon: 63 },
    { name: "South China Sea", lat: 14, lon: 114 },
    { name: "Tasman Sea", lat: -38, lon: 161 }
  ];
  // Ocean names breathe: the tracking opens up as you zoom in. pretext takes
  // letter-spacing as a px number at prepare() time, so the value is quantized
  // to four steps and each (name, step) is prepared at most once for the life
  // of the page — a zoom never triggers a new prepare().
  const OCEAN_LS_EM = [0.18, 0.22, 0.26, 0.30];

  // Prepared-handle caches. Keyed by content, so they survive a rebuild
  // (resize) untouched — the label fonts are fixed px sizes, independent of
  // the map's cell size.
  const nameHandles = new Map();    // place id -> handle (name, uppercased)
  const nativeHandles = new Map();  // place id -> handle (native name) or null
  const tagHandles = new Map();     // place id -> handle (tagline)
  const oceanHandles = new Map();   // name + "|" + step -> handle
  function makeHandle(text, role) {
    const str = String(text == null ? "" : text).replace(/\s+/g, " ").trim();
    return {
      text: str,
      // CSS paints a letter-space after the last grapheme too; pretext counts
      // only the gaps between them. Carrying the difference as `ls` keeps the
      // routed width and the painted width the same number.
      ls: role.letterSpacing || 0,
      pre: prepareWithSegments(str, role.font,
        role.letterSpacing ? { letterSpacing: role.letterSpacing } : undefined)
    };
  }
  function nameHandleFor(x) {
    let h = nameHandles.get(x.p.id);
    // .map-label is `text-transform: uppercase` and pretext does not model
    // text-transform, so the string is uppercased before it is measured.
    if (!h) { h = makeHandle(String(x.p.name).toUpperCase(), ROLE_LABEL); nameHandles.set(x.p.id, h); }
    return h;
  }
  // The name in its own script, for the label's middle line. Only a genuinely
  // different name earns a line; the handle comes from js/text.js when it is
  // there, because that is the one prepared under the place's own locale (and
  // with word-break: keep-all for CJK). Never uppercased.
  function nativeTextFor(p) {
    if (!FLAGS.nativeNames) return "";
    const s = String(p.nativeName || "");
    return !s || s === p.name ? "" : s;
  }
  function nativeHandleFor(x) {
    if (!ROLE_NATIVE) return null;
    if (nativeHandles.has(x.p.id)) return nativeHandles.get(x.p.id);
    const text = nativeTextFor(x.p);
    let h = null;
    if (text) {
      const T = window.ATLAS_TEXT;
      if (T && typeof T.handleFor === "function") {
        try {
          h = { text: text, ls: ROLE_NATIVE.letterSpacing || 0,
                pre: T.handleFor("map-label-native", x.p.id) };
        } catch (e) { h = null; }
      }
      if (!h) h = makeHandle(text, ROLE_NATIVE);
    }
    nativeHandles.set(x.p.id, h);
    return h;
  }
  // Which way the native name runs. pretext's richer handle carries an
  // approximate bidi level per segment; the first strong (text) segment
  // decides, and the BCP 47 tag is only the fallback for a string with no
  // strong RTL character at all.
  function nativeDirFor(x) {
    const h = nativeHandleFor(x);
    const fallback = dirForLang(x.p.nativeLang);
    return h ? directionFromLevels(h.pre, fallback) : fallback;
  }
  function tagHandleFor(x) {
    if (!ROLE_TAG) return null;
    let h = tagHandles.get(x.p.id);
    if (!h) { h = makeHandle(x.p.tagline, ROLE_TAG); tagHandles.set(x.p.id, h); }
    return h;
  }
  function oceanHandleFor(name, step) {
    const key = name + "|" + step;
    let h = oceanHandles.get(key);
    if (!h) {
      const ls = OCEAN_LS_EM[step] * fontPxOf(ROLE_OCEAN);
      h = makeHandle(name.toUpperCase(), { font: ROLE_OCEAN.font, letterSpacing: ls });
      oceanHandles.set(key, h);
    }
    return h;
  }

  // Anchor directions, tried in this order at each offset. `dir` is the
  // direction the text runs (+1 east, −1 west); `pen` biases the score so a
  // label prefers to sit beside its dot rather than above or below it.
  const LABEL_DIRS = [
    { dc: 1, dr: 0, dir: 1, pen: 0 },    // E
    { dc: -1, dr: 0, dir: -1, pen: 1 },  // W
    { dc: 0, dr: -1, dir: 1, pen: 4 },   // N
    { dc: 0, dr: 1, dir: 1, pen: 4 },    // S
    { dc: 1, dr: -1, dir: 1, pen: 6 },   // NE
    { dc: 1, dr: 1, dir: 1, pen: 6 },    // SE
    { dc: -1, dr: -1, dir: -1, pen: 7 }, // NW
    { dc: -1, dr: 1, dir: -1, pen: 7 }   // SW
  ];

  // One byte per grid cell, cleared on every placement.
  const occupancy = new Uint8Array(COLS * ROWS);
  let labelRecords = [];
  let oceanRecords = [];
  const labelEls = new Map();   // place id -> { el, lines: [span] }
  const oceanEls = [];          // reused span pool
  let markersEl = null;
  let placementQueued = false, lastTier = -1, lastPlaceZoom = -1;
  let visibleIds = null;        // search / category filter, null = everything
  const placeStats = { placements: 0, lastMs: 0, totalMs: 0 };

  const DEBUG_MAP = (function () {
    try {
      const h = location.hostname;
      if (h === "localhost" || h === "127.0.0.1" || h === "[::1]" || h === "::1") return true;
      return new URLSearchParams(location.search).get("debug") === "map";
    } catch (e) { return false; }
  })();

  function tierFor(z) { return z >= TIER_TAG_Z ? 2 : (z >= TIER_NAME_Z ? 1 : 0); }
  const toGridCol = (lon) => Math.max(0, Math.min(COLS - 1, Math.round(((lon + 180) / 360) * COLS)));
  const toGridRow = (lat) => Math.max(0, Math.min(ROWS - 1, Math.round(((90 - lat) / 180) * ROWS)));

  // Free water cells on `row`, starting at `col` and walking in `dir`.
  function freeRun(row, col, dir, limit) {
    if (row < 0 || row >= ROWS) return 0;
    let n = 0, c = col;
    while (n < limit && c >= 0 && c < COLS) {
      const i = row * COLS + c;
      if (kind[i] || occupancy[i]) break;
      n++; c += dir;
    }
    return n;
  }

  // The cells a rendered label covers, derived from the geometry that also
  // positions it: the anchor cell, the run direction, and each line's painted
  // width. Placement marks these; checkLabels() re-walks them.
  function cellsOf(rec) {
    const out = [];
    for (const line of rec.lines) {
      const cells = Math.max(1, Math.ceil((line.width - 0.001) / rec.cellW));
      const c0 = rec.dir > 0 ? rec.col : rec.col - cells + 1;
      out.push({ row: line.row, c0: c0, c1: c0 + cells - 1 });
    }
    return out;
  }
  function markCells(cells) {
    for (const s of cells) {
      if (s.row < 0 || s.row >= ROWS) continue;
      const base = s.row * COLS;
      for (let c = Math.max(0, s.c0); c <= Math.min(COLS - 1, s.c1); c++) occupancy[base + c] = 1;
    }
  }

  // ---- Routing one candidate ---------------------------------------------
  // Read the free run on each row the label would use, hand those widths to
  // the pure router one row at a time, and let it say whether the whole string
  // survived. A candidate that would have to break a word mid-word comes back
  // incomplete and is discarded.
  function routeAt(handle, anchorRow, anchorCol, dir, cellW, maxLines, startRow) {
    const widths = [];
    for (let i = 0; i < maxLines; i++) {
      widths.push(freeRun(startRow + i, anchorCol, dir, LABEL_RUN_LIMIT) * cellW);
    }
    return routeText(handle.pre, widths, 1, {
      maxLines: maxLines,
      text: handle.text,
      startRow: startRow,
      extraWidth: handle.ls,
      minWidth: cellW,         // a single free cell is not worth a line
      // The lines are painted as one stacked block, so they must live on
      // consecutive rows: a blocked row ends this candidate rather than being
      // skipped over. (Without this the next line renders one row higher than
      // it was routed for, straight onto its neighbour's name.)
      contiguous: true
    });
  }

  // Best anchor for one marker, or null when the name cannot be fitted into
  // the sea anywhere near it at this zoom.
  function findAnchor(x, tier, cellW) {
    const nameH = nameHandleFor(x);
    const nativeH = tier >= 2 ? nativeHandleFor(x) : null;
    const tagH = tier >= 2 ? tagHandleFor(x) : null;
    let best = null;
    for (let off = 1; off <= LABEL_MAX_OFFSET; off++) {
      for (const d of LABEL_DIRS) {
        const col = x.gcol + d.dc * off;
        const row = x.grow + d.dr * off;
        if (col < 0 || col >= COLS || row < 0 || row >= ROWS) continue;
        if (kind[row * COLS + col] || occupancy[row * COLS + col]) continue;
        const name = routeAt(nameH, row, col, d.dir, cellW, NAME_MAX_LINES, row);
        if (!name.complete || !name.lines.length) continue;
        let from = name.lines[name.lines.length - 1].row + 1;
        // The native name takes the rows straight under the Latin one; if the
        // water there is too narrow for it the label falls back to name +
        // tagline rather than losing the anchor altogether.
        let nativeLines = [];
        if (nativeH) {
          const nat = routeAt(nativeH, row, col, d.dir, cellW, NATIVE_MAX_LINES, from);
          if (nat.complete && nat.lines.length) {
            nativeLines = nat.lines;
            from = nat.lines[nat.lines.length - 1].row + 1;
          }
        }
        let tagLines = [];
        if (tagH) {
          const tag = routeAt(tagH, row, col, d.dir, cellW, TAG_MAX_LINES, from);
          if (tag.complete) tagLines = tag.lines;
        }
        const score = name.lines.length * 100 + off * 12 + d.pen +
          (tagH && !tagLines.length ? 40 : 0) +
          (nativeH && !nativeLines.length ? 20 : 0);
        if (!best || score < best.score) {
          best = {
            score: score, row: row, col: col, dir: d.dir,
            nameLines: name.lines, nativeLines: nativeLines, tagLines: tagLines
          };
        }
      }
      if (best) break;   // nearest offset that works wins; distance matters
    }
    return best;
  }

  // ---- Rendering ----------------------------------------------------------
  // The label is a child of the marker layer, so it pans and zooms with the
  // map, and counter-scales by 1/--zoom (the same trick the markers use) so it
  // stays a constant size on screen. A west-running label is pinned by its
  // right edge instead of its left, so the text always ends at the anchor cell
  // no matter how the measured and painted widths round.
  function ensureLabelEl(x) {
    let entry = labelEls.get(x.p.id);
    if (entry) return entry;
    const el = document.createElement("span");
    el.className = "map-label";
    el.dataset.placeId = x.p.id;
    // The marker button already announces "<name>, <country> — open field
    // note"; a second copy here would make every place read twice.
    el.setAttribute("aria-hidden", "true");
    el.addEventListener("mouseenter", function () { if (x.enter) x.enter(); });
    el.addEventListener("mouseleave", function () { if (x.leave) x.leave(); });
    el.addEventListener("click", function (e) {
      e.stopPropagation();
      const hash = "#/place/" + encodeURIComponent(x.p.id);
      if (location.hash !== hash) location.hash = hash;
    });
    entry = { el: el, lines: [] };
    labelEls.set(x.p.id, entry);
    if (markersEl) markersEl.appendChild(el);
    return entry;
  }

  function renderLabel(x, rec) {
    const entry = ensureLabelEl(x);
    const el = entry.el;
    const texts = rec.lines.map(function (l) { return l.text; });
    while (entry.lines.length < texts.length) {
      const span = document.createElement("span");
      span.className = "map-label-line";
      el.appendChild(span);
      entry.lines.push(span);
    }
    while (entry.lines.length > texts.length) entry.lines.pop().remove();
    const nativeEnd = rec.nameCount + rec.nativeCount;
    for (let i = 0; i < texts.length; i++) {
      const span = entry.lines[i];
      if (span.textContent !== texts[i]) span.textContent = texts[i];
      const isNative = i >= rec.nameCount && i < nativeEnd;
      const isTag = i >= nativeEnd;
      if (span.classList.contains("map-label-native") !== isNative) {
        span.classList.toggle("map-label-native", isNative);
      }
      if (span.classList.contains("map-label-tag") !== isTag) span.classList.toggle("map-label-tag", isTag);
      // The native lines carry their own language and direction; the Latin
      // ones inherit the document's.
      if (isNative) {
        if (rec.nativeLang) span.setAttribute("lang", rec.nativeLang);
        else span.removeAttribute("lang");
        span.setAttribute("dir", rec.nativeDir || "ltr");
      } else if (span.hasAttribute("dir")) {
        span.removeAttribute("dir");
        span.removeAttribute("lang");
      }
    }
    el.style.setProperty("top", (rec.lines[0].row * LINEH) + "px");
    if (rec.dir > 0) {
      el.style.removeProperty("right");
      el.style.setProperty("left", (rec.col * CHARW) + "px");
      if (el.dataset.dir !== "right") el.dataset.dir = "right";
    } else {
      el.style.removeProperty("left");
      el.style.setProperty("right", (mapW - (rec.col + 1) * CHARW) + "px");
      if (el.dataset.dir !== "left") el.dataset.dir = "left";
    }
    if (!el.classList.contains("is-placed")) el.classList.add("is-placed");
  }

  function hideLabel(x) {
    const entry = labelEls.get(x.p.id);
    if (entry && entry.el.classList.contains("is-placed")) entry.el.classList.remove("is-placed");
  }

  function oceanEl(index) {
    let el = oceanEls[index];
    if (el) return el;
    el = document.createElement("span");
    el.className = "map-ocean-label";
    el.setAttribute("aria-hidden", "true");
    oceanEls[index] = el;
    if (markersEl) markersEl.appendChild(el);
    return el;
  }

  // ---- Ocean and sea names ------------------------------------------------
  // One row of free water, centred on the anchor and allowed to slide along
  // the row to find it. Marked into the occupancy mask before any place label
  // is routed, so place names flow around the ocean names rather than over
  // them.
  const OCEAN_SLIDE = 16;
  function placeOceanLabels(cellW, z) {
    const t = Math.max(0, Math.min(1, (z - 1) / (TIER_TAG_Z - 1)));
    const step = Math.round(t * (OCEAN_LS_EM.length - 1));
    const lsPx = OCEAN_LS_EM[step] * fontPxOf(ROLE_OCEAN);
    let used = 0;
    for (const ocean of OCEANS) {
      const handle = oceanHandleFor(ocean.name, step);
      const width = measureNaturalWidth(handle.pre) + handle.ls;
      const need = Math.max(1, Math.ceil((width - 0.001) / cellW));
      const row = toGridRow(ocean.lat);
      const centre = toGridCol(ocean.lon) - Math.floor(need / 2);
      let start = -1;
      for (let slide = 0; slide <= OCEAN_SLIDE && start < 0; slide++) {
        const tries = slide === 0 ? [0] : [-slide, slide];
        for (const delta of tries) {
          const c0 = centre + delta;
          if (c0 < 0 || c0 + need > COLS) continue;
          let ok = true;
          for (let k = 0; k < need; k++) {
            const i = row * COLS + c0 + k;
            if (kind[i] || occupancy[i]) { ok = false; break; }
          }
          if (ok) { start = c0; break; }
        }
      }
      if (start < 0) continue;   // no room on this grid at this zoom
      const rec = {
        id: ocean.name, row: row, col: start, dir: 1, cellW: cellW,
        nameCount: 1, lines: [{ text: handle.text, width: width, row: row }]
      };
      rec.cells = cellsOf(rec);
      markCells(rec.cells);
      oceanRecords.push(rec);
      const el = oceanEl(used++);
      if (el.textContent !== handle.text) el.textContent = handle.text;
      el.style.setProperty("letter-spacing", (Math.round(lsPx * 100) / 100) + "px");
      el.style.setProperty("left", (start * CHARW) + "px");
      el.style.setProperty("top", (row * LINEH) + "px");
      if (!el.classList.contains("is-placed")) el.classList.add("is-placed");
    }
    for (let i = used; i < oceanEls.length; i++) oceanEls[i].classList.remove("is-placed");
  }
  function hideOceanLabels() {
    for (const el of oceanEls) el.classList.remove("is-placed");
  }

  // ---- One placement pass -------------------------------------------------
  function placeLabels() {
    if (!markersEl || !view) return;
    const started = performance.now();
    const z = view.zoom;
    const cellW = CHARW * z;                 // one grid cell, in screen px
    const tier = LABELS_ON ? tierFor(z) : 0;
    occupancy.fill(0);
    labelRecords = [];
    oceanRecords = [];

    // The dots come first: no label may sit under one. A dot is a constant
    // 19px on screen, so the number of cells it covers shrinks as you zoom in.
    const dotCells = Math.max(0, Math.ceil((MARKER_PX / 2) / cellW) - 1);
    for (const x of places) {
      if (!x.pos) continue;
      if (visibleIds && !visibleIds.has(x.p.id)) continue;
      for (let dr = -dotCells; dr <= dotCells; dr++) {
        const rr = x.grow + dr;
        if (rr < 0 || rr >= ROWS) continue;
        for (let dc = -dotCells; dc <= dotCells; dc++) {
          const cc = x.gcol + dc;
          if (cc < 0 || cc >= COLS) continue;
          occupancy[rr * COLS + cc] = 1;
        }
      }
    }

    if (OCEAN_ON) placeOceanLabels(cellW, z);
    else hideOceanLabels();

    for (const x of places) {
      if (tier === 0 || !x.pos || (visibleIds && !visibleIds.has(x.p.id))) { hideLabel(x); continue; }
      const best = findAnchor(x, tier, cellW);
      if (!best) { hideLabel(x); continue; }
      const rec = {
        id: x.p.id, row: best.row, col: best.col, dir: best.dir, cellW: cellW,
        nameCount: best.nameLines.length,
        nativeCount: best.nativeLines.length,
        nativeLang: best.nativeLines.length ? (x.p.nativeLang || "") : "",
        nativeDir: best.nativeLines.length ? nativeDirFor(x) : "ltr",
        lines: best.nameLines.concat(best.nativeLines, best.tagLines)
      };
      rec.cells = cellsOf(rec);
      markCells(rec.cells);
      labelRecords.push(rec);
      renderLabel(x, rec);
    }

    lastTier = tier;
    lastPlaceZoom = z;
    placeStats.placements++;
    placeStats.lastMs = performance.now() - started;
    placeStats.totalMs += placeStats.lastMs;

    if (DEBUG_MAP) {
      const report = checkLabels();
      if (report.overlaps) {
        // eslint-disable-next-line no-console
        console.warn("[atlas:map] " + report.overlaps + " label cell(s) overlap land or another label", report);
      }
    }
  }

  // At most one placement per frame, whatever asks for it.
  function requestPlacement() {
    if (!LABELS_ON && !OCEAN_ON) return;
    if (placementQueued) return;
    placementQueued = true;
    requestAnimationFrame(function () {
      placementQueued = false;
      placeLabels();
    });
  }

  // ---- Dev assertion ------------------------------------------------------
  // Walk every rendered label's cells against the land mask and against a
  // freshly built occupancy mask. Runs automatically after each placement on
  // localhost or with ?debug=map, and scripts/smoke.mjs calls it directly.
  function checkLabels() {
    const seen = new Uint8Array(COLS * ROWS);
    const problems = [];
    let overlaps = 0;
    const walk = function (rec, what) {
      for (const s of cellsOf(rec)) {
        for (let c = s.c0; c <= s.c1; c++) {
          if (s.row < 0 || s.row >= ROWS || c < 0 || c >= COLS) {
            overlaps++; problems.push({ what: what, id: rec.id, row: s.row, col: c, why: "off-grid" });
            continue;
          }
          const i = s.row * COLS + c;
          if (kind[i]) {
            overlaps++; problems.push({ what: what, id: rec.id, row: s.row, col: c, why: "land" });
          } else if (seen[i]) {
            overlaps++; problems.push({ what: what, id: rec.id, row: s.row, col: c, why: "label" });
          }
          seen[i] = 1;
        }
      }
    };
    for (const rec of oceanRecords) walk(rec, "ocean");
    for (const rec of labelRecords) walk(rec, "place");
    return {
      labels: labelRecords.length,
      oceanLabels: oceanRecords.length,
      overlaps: overlaps,
      lines: labelRecords.reduce(function (n, r) { return n + r.lines.length; }, 0),
      tier: lastTier,
      zoom: view ? view.zoom : 0,
      problems: problems.slice(0, 20)
    };
  }

  // The same walk, but starting from the DOM instead of the placement record:
  // every painted line box is mapped back onto the grid through
  // getBoundingClientRect(). It is the slow, independent version of
  // checkLabels() — it also proves the CSS half of the contract (the
  // 1/--zoom counter-scale, the --row-h line box, the left/right pinning) is
  // doing what the routing assumed. scripts/smoke.mjs runs it once per zoom.
  function checkPainted() {
    const problems = [];
    let boxes = 0, overlaps = 0;
    if (!zoomEl) return { boxes: 0, overlaps: 0, problems: problems };
    const origin = zoomEl.getBoundingClientRect();
    const z = view ? view.zoom : 1;
    const seen = new Uint8Array(COLS * ROWS);
    const EPS = 0.2;   // ignore a cell a box merely grazes
    const walk = function (el, what, id) {
      const r = el.getBoundingClientRect();
      if (!r.width || !r.height) return;
      boxes++;
      const c0 = Math.floor((r.left - origin.left) / z / CHARW + EPS);
      const c1 = Math.ceil((r.right - origin.left) / z / CHARW - EPS) - 1;
      const r0 = Math.floor((r.top - origin.top) / z / LINEH + EPS);
      const r1 = Math.ceil((r.bottom - origin.top) / z / LINEH - EPS) - 1;
      for (let row = r0; row <= r1; row++) {
        for (let col = c0; col <= c1; col++) {
          if (row < 0 || row >= ROWS || col < 0 || col >= COLS) {
            overlaps++; problems.push({ what: what, id: id, row: row, col: col, why: "off-grid" });
            continue;
          }
          const i = row * COLS + col;
          if (kind[i]) { overlaps++; problems.push({ what: what, id: id, row: row, col: col, why: "land" }); }
          else if (seen[i]) { overlaps++; problems.push({ what: what, id: id, row: row, col: col, why: "label" }); }
          seen[i] = 1;
        }
      }
    };
    for (const el of document.querySelectorAll(".map-ocean-label.is-placed")) walk(el, "ocean", el.textContent);
    for (const el of document.querySelectorAll(".map-label.is-placed")) {
      const id = el.dataset.placeId || "";
      for (const line of el.querySelectorAll(".map-label-line")) walk(line, "place", id);
    }
    return { boxes: boxes, overlaps: overlaps, problems: problems.slice(0, 20) };
  }

  // ---- Debug / test surface ----------------------------------------------
  // Not a public API: scripts/smoke.mjs drives the map through this instead of
  // synthesising pointer events, and it is what makes the overlap assertion
  // and the zoom-frame timing reproducible.
  let showCardRef = null, hideCardRef = null, cardNativeLinesRef = null;
  window.ATLAS_MAP_DEBUG = {
    enabled: DEBUG_MAP,
    flags: {
      labels: LABELS_ON, oceanLabels: OCEAN_ON, hoverFit: FLAGS.hoverFit,
      nativeNames: FLAGS.nativeNames && !!ROLE_NATIVE
    },
    tiers: { name: TIER_NAME_Z, tagline: TIER_TAG_Z },
    getZoom: function () { return view ? view.zoom : 1; },
    // The same call the +/− buttons make: zoom about the viewport centre.
    setZoom: function (z) {
      if (!view) return 0;
      vpW = viewport.clientWidth || vpW;
      vpH = viewport.clientHeight || vpH;
      zoomTo(z, vpW / 2, vpH / 2);
      return view.zoom;
    },
    place: function () { placeLabels(); return checkLabels(); },
    checkLabels: checkLabels,
    checkPainted: checkPainted,
    stats: function () {
      return {
        placements: placeStats.placements,
        lastMs: placeStats.lastMs,
        avgMs: placeStats.placements ? placeStats.totalMs / placeStats.placements : 0
      };
    },
    labels: function () {
      return labelRecords.map(function (r) {
        return {
          id: r.id, row: r.row, col: r.col, dir: r.dir,
          lines: r.lines.map(function (l) { return { text: l.text, width: l.width, row: l.row }; }),
          cells: cellsOf(r)
        };
      });
    },
    oceanLabels: function () {
      return oceanRecords.map(function (r) { return { name: r.id, row: r.row, col: r.col }; });
    },
    showCard: function (id) {
      const x = places.find(function (p) { return p.p.id === id; });
      if (!x || !showCardRef) return null;
      showCardRef(x);
      const nativeEl = card ? card.querySelector(".map-card-native") : null;
      return {
        id: id,
        width: parseFloat(card && card.style.width) || 0,
        lines: (card ? card.querySelector(".map-card-tag").textContent : "").split("\n"),
        // The native-name line, as planned and as rendered. scripts/smoke.mjs
        // reads the painted line boxes off this element.
        native: nativeEl && !nativeEl.hidden ? {
          text: nativeEl.textContent,
          lang: nativeEl.getAttribute("lang"),
          dir: nativeEl.getAttribute("dir"),
          wordBreak: nativeEl.getAttribute("data-wb") || "normal",
          predictedLines: cardNativeLinesRef ? cardNativeLinesRef(x) : 0
        } : null
      };
    },
    // The label's own middle line, per placed label.
    nativeLabels: function () {
      return labelRecords.filter(function (r) { return r.nativeCount; })
        .map(function (r) {
          return {
            id: r.id, lang: r.nativeLang, dir: r.nativeDir, lines: r.nativeCount,
            text: r.lines.slice(r.nameCount, r.nameCount + r.nativeCount)
              .map(function (l) { return l.text; })
          };
        });
    },
    hideCard: function () { if (hideCardRef) hideCardRef(); }
  };

  // ---- Mutable per-build state -------------------------------------------
  let PX, LINEH, CHARW, mapW, mapH;
  let disp, vel, animId = 0, ambientTimer = null, hoverTimer = null, hoveredX = null;
  let stage, card, cardVisibleId = null;
  // Off-screen pause: when the map scrolls out of view we stop the animation
  // loop and ambient timer (they otherwise run for the page's whole life).
  let viewportVisible = true, waveT0 = 0, frameRef = null, loopRunning = false;
  // Pan/zoom view. The map content lives in a `.map-zoom` wrapper (sized mapW×mapH)
  // that we scale about its centre and translate in screen px. The stage itself
  // stays untransformed (just centred) so pointer→map math stays exact.
  let view, panX, panY, zoomEl, vpW = 0, vpH = 0;
  const ZOOM_MIN = 1, ZOOM_MAX = 4;
  function clamp(v, a, b) { return Math.max(a, Math.min(b, v)); }
  // Pointer (stage-local sx,sy) → map-local px,py under the current view.
  function toMap(sx, sy) {
    return {
      x: (sx - mapW / 2 - panX) / view.zoom + mapW / 2,
      y: (sy - mapH / 2 - panY) / view.zoom + mapH / 2
    };
  }
  // Map-local → stage-local (where non-scaling UI like the card/crosshair live).
  function toStage(px, py) {
    return {
      x: (px - mapW / 2) * view.zoom + panX + mapW / 2,
      y: (py - mapH / 2) * view.zoom + panY + mapH / 2
    };
  }
  function clampPan() {
    const overX = Math.max(0, (mapW * view.zoom - vpW) / 2);
    const overY = Math.max(0, (mapH * view.zoom - vpH) / 2);
    panX = clamp(panX, -overX, overX);
    panY = clamp(panY, -overY, overY);
  }
  // Start the animation loop if it isn't already running (the off-screen
  // observer and the first build can both want to start it).
  function startLoop() {
    if (!frameRef || loopRunning) return;
    loopRunning = true;
    animId = requestAnimationFrame(frameRef);
  }
  function applyView() {
    if (!zoomEl) return;
    zoomEl.style.transform = "translate(" + panX + "px, " + panY + "px) scale(" + view.zoom + ")";
    // Counter-scale so markers and labels keep a constant on-screen size at any
    // zoom (CSS uses 1 / var(--zoom) for their dimensions).
    zoomEl.style.setProperty("--zoom", String(view.zoom));
    // Panning moves labels with the map and changes nothing about where they
    // fit; only a zoom does. Re-route when the tier flips or the zoom has
    // drifted past a step — debounced to one placement per frame.
    if (tierFor(view.zoom) !== lastTier || Math.abs(view.zoom - lastPlaceZoom) > ZOOM_STEP) {
      requestPlacement();
    }
  }
  // Zoom so that the map point under stage-local (sx,sy) stays fixed there.
  function zoomTo(newZoom, sx, sy) {
    const z1 = clamp(newZoom, ZOOM_MIN, ZOOM_MAX);
    const p = toMap(sx, sy);
    view.zoom = z1;
    panX = sx - mapW / 2 - (p.x - mapW / 2) * z1;
    panY = sy - mapH / 2 - (p.y - mapH / 2) * z1;
    clampPan();
    applyView();
  }
  // Wave phase + per-region bias (computed at build so the ocean has a stable
  // regional character; the time-varying sines in frame() make it travel).
  let phase, waveBias, waterList, waterLen = 0;
  // Marker elements for the currently built map (reset each build). Search
  // and category filtering dim the ones that don't match, so the map mirrors
  // the grid instead of always showing every dot.
  let markerRefs = [];

  function computePX() {
    const vw = viewport.clientWidth || 1200;
    const vh = viewport.clientHeight || 700;
    const px = Math.min(vw / (COLS * UNIT), vh / (ROWS * ROW_FACTOR));
    return Math.max(PX_MIN, Math.min(PX_MAX, px));
  }

  function clearBuild() {
    if (animId) cancelAnimationFrame(animId);
    if (ambientTimer) { clearInterval(ambientTimer); ambientTimer = null; }
    if (hoverTimer) { clearInterval(hoverTimer); hoverTimer = null; }
    if (stage) stage.remove();
    stage = null; card = null; cardVisibleId = null; hoveredX = null;
    zoomEl = null;
    loopRunning = false;
    if (view) { view.zoom = 1; }
    panX = 0; panY = 0;
    // The label DOM went with the stage; drop the element cache (the prepared
    // pretext handles are keyed by text and deliberately survive a rebuild).
    markersEl = null;
    labelEls.clear();
    oceanEls.length = 0;
    labelRecords = [];
    oceanRecords = [];
    lastTier = -1; lastPlaceZoom = -1;
  }

  function build() {
    clearBuild();
    PX = computePX();
    LINEH = PX * ROW_FACTOR;
    const probe = document.createElement("canvas").getContext("2d");
    probe.font = PX + "px " + MONO;
    CHARW = probe.measureText("MMMMMMMMMM").width / 10;
    mapW = COLS * CHARW;
    mapH = ROWS * LINEH;
    const FONT = PX + "px " + MONO;
    view = { zoom: 1 };
    panX = 0; panY = 0;
    vpW = viewport.clientWidth || mapW;
    vpH = viewport.clientHeight || mapH;

    disp = new Float32Array(COLS * ROWS);
    vel = new Float32Array(COLS * ROWS);

    // Wave phase + regional bias. Phase tilts wave fronts slightly per region
    // so swell arrives at different places at different times (real seas
    // interfere rather than scroll uniformly); bias gives each region a
    // characterful base energy (some seas are just rougher).
    phase = new Float32Array(COLS * ROWS);
    waveBias = new Float32Array(COLS * ROWS);
    waterList = waterCells;
    waterLen = waterCells.length;
    for (let i = 0; i < COLS * ROWS; i++) {
      if (kind[i]) continue;
      const c = i % COLS, r = (i / COLS) | 0;
      phase[i] = c * 0.21 + r * 0.09;
      waveBias[i] = 0.5 + 0.5 * Math.sin(c * 0.11 + r * 0.17); // 0..1
    }

    function stir(c, r, amp) {
      c = Math.round(c); r = Math.round(r);
      if (c < 0 || c >= COLS || r < 0 || r >= ROWS) return;
      const i = r * COLS + c;
      if (!kind[i]) { disp[i] += amp; return; }
      // Land tapped: ripple the nearest water ring instead.
      for (let rad = 1; rad <= 8; rad++) {
        for (let dr = -rad; dr <= rad; dr++) {
          for (let dc = -rad; dc <= rad; dc++) {
            if (Math.max(Math.abs(dr), Math.abs(dc)) !== rad) continue;
            const rr = r + dr, cc = c + dc;
            if (rr < 0 || rr >= ROWS || cc < 0 || cc >= COLS) continue;
            const j = rr * COLS + cc;
            if (!kind[j]) { disp[j] += amp * 0.6; return; }
          }
        }
      }
    }

    // ---- Stage ----------------------------------------------------------
    stage = document.createElement("div");
    stage.className = "map-stage";
    stage.style.width = mapW + "px";
    stage.style.height = mapH + "px";
    stage.style.fontFamily = MONO;
    stage.style.fontSize = PX + "px";
    stage.style.lineHeight = LINEH + "px";
    viewport.appendChild(stage);

    // All the visual layers (base, sea, clouds, markers) live inside this
    // wrapper so pan/zoom can transform them as one unit. The crosshair,
    // readout and hover card stay on the stage (untransformed) so they keep a
    // constant on-screen size regardless of zoom.
    zoomEl = document.createElement("div");
    zoomEl.className = "map-zoom";
    zoomEl.style.width = mapW + "px";
    zoomEl.style.height = mapH + "px";
    // One grid row, in map px. Label line boxes are `calc(var(--row-h) *
    // var(--zoom))` tall, which — under the 1/--zoom counter-scale — is exactly
    // one grid row on screen, so a routed line and a painted line share cells.
    zoomEl.style.setProperty("--row-h", LINEH + "px");
    stage.appendChild(zoomEl);

    // ---- Base canvas: static land + faint sea floor (drawn once) ------------
    // The animated water (traveling waves + ripples) lives on the sea canvas
    // canvas above this; keeping the base static makes each frame cheap.
    const base = document.createElement("canvas");
    base.width = Math.round(mapW * DPR);
    base.height = Math.round(mapH * DPR);
    base.className = "map-base";
    base.style.width = mapW + "px";
    base.style.height = mapH + "px";
    zoomEl.appendChild(base);
    const bctx = base.getContext("2d");
    bctx.scale(DPR, DPR);
    bctx.font = FONT;
    bctx.textBaseline = "middle";
    bctx.textAlign = "left";
    for (let r = 0; r < ROWS; r++) {
      const rowBase = r * COLS;
      const y = (r + 0.5) * LINEH;
      for (let c = 0; c < COLS; c++) {
        const i = rowBase + c;
        const x = c * CHARW;
        if (kind[i]) {
          bctx.fillStyle = PALETTE[cellColor[i]];
          bctx.fillText(String.fromCharCode(cellGlyph[i]), x, y);
        } else {
          bctx.fillStyle = "rgba(80, 130, 170, 0.10)";
          bctx.fillText("·", x, y);
        }
      }
    }

    const sea = document.createElement("canvas");
    sea.width = Math.round(mapW * DPR);
    sea.height = Math.round(mapH * DPR);
    sea.className = "map-sea";
    sea.style.width = mapW + "px";
    sea.style.height = mapH + "px";
    zoomEl.appendChild(sea);
    const sctx = sea.getContext("2d");
    sctx.scale(DPR, DPR);
    sctx.font = FONT;
    sctx.textBaseline = "middle";
    sctx.textAlign = "left";

    // ---- Cloud layer --------------------------------------------------------
    // A handful of drifting white clouds crossing the map (land and sea).
    // Each cloud is a cluster of 3..5 independently wobbling, slowly rotating
    // sub-puffs, so the silhouette morphs continuously (less blocky than a
    // single stamped sprite). Each cloud fades out near the pole — the
    // Antarctica rows are already white ice, so the fade makes the white
    // dissolve into the white instead of reading as an opaque band. The
    // canvas sits above the sea and below the markers so a dot stays visible
    // when a cloud passes.
    const cloudsEl = document.createElement("canvas");
    cloudsEl.width = Math.round(mapW);   // 1x is plenty for soft blobs
    cloudsEl.height = Math.round(mapH);
    cloudsEl.className = "map-sea";      // reuse the absolute-position style
    cloudsEl.style.width = mapW + "px";
    cloudsEl.style.height = mapH + "px";
    zoomEl.appendChild(cloudsEl);
    const cctx = cloudsEl.getContext("2d");

    const CLOUD_N = isMobile ? 4 : 6;
    // Pre-render several soft, lumpy cloud sprites (random radial-gradient
    // lobes). Several distinct shapes plus per-cloud sub-puff clusters keep
    // the outline from looking like a repeating blocky blob.
    function makeCloudSprite() {
      const W = 360, H = 200;
      const cv = document.createElement("canvas");
      cv.width = W; cv.height = H;
      const sc = cv.getContext("2d");
      const n = 5 + ((Math.random() * 3) | 0); // 5..7 lobes
      for (let l = 0; l < n; l++) {
        const bx = 0.20 + Math.random() * 0.60;
        const by = 0.26 + Math.random() * 0.48;
        const br = (0.15 + Math.random() * 0.20) * W;
        const g = sc.createRadialGradient(bx * W, by * H, 0, bx * W, by * H, br);
        g.addColorStop(0, "rgba(248, 251, 254, 0.92)");
        g.addColorStop(0.45, "rgba(242, 247, 252, 0.42)");
        g.addColorStop(1, "rgba(238, 245, 252, 0)");
        sc.fillStyle = g;
        sc.fillRect(0, 0, W, H);
      }
      return cv;
    }
    const sprites = [makeCloudSprite(), makeCloudSprite(), makeCloudSprite()];
    const clouds = [];
    for (let k = 0; k < CLOUD_N; k++) {
      const wPx = (0.18 + Math.random() * 0.16) * mapW;   // cloud footprint
      const hPx = wPx * 0.5;
      const cy = (0.08 + Math.random() * 0.55) * mapH;    // stays clear of the white polar strip
      const nSub = 3 + ((Math.random() * 3) | 0);         // 3..5 sub-puffs
      const sub = [];
      for (let s = 0; s < nSub; s++) {
        sub.push({
          spr: (Math.random() * sprites.length) | 0,
          ox: (Math.random() - 0.5) * 0.9 * wPx,           // rest offset from center
          oy: (Math.random() - 0.5) * 0.7 * hPx,
          sw: 0.06 + Math.random() * 0.10,                // wobble speed
          sa: (0.15 + Math.random() * 0.20) * wPx,        // wobble amplitude (x)
          sb: (0.10 + Math.random() * 0.18) * hPx,        // wobble amplitude (y)
          ph: Math.random() * 6.283,
          size: (0.5 + Math.random() * 0.55) * wPx,       // sub-puff sprite width
          rs: -0.5 + Math.random(),                        // rad/s slow rotation
          al: 0.28 + Math.random() * 0.24                 // sub-puff alpha
        });
      }
      clouds.push({
        x: Math.random() * mapW,
        y: cy, w: wPx, h: hPx,
        v: 0.22 + Math.random() * 0.22,                   // px/frame, west→east
        ph: Math.random() * 6.283,
        sp: 0.05 + Math.random() * 0.06,
        sub
      });
    }
    // Per-cloud Antarctic fade from each sub-puff's rest row.
    for (const cl of clouds) {
      let f = 1;
      for (const s of cl.sub) f = Math.min(f, cloudFade((cl.y + s.oy) / LINEH));
      cl.fade = f;
    }
    function drawClouds(t) {
      cctx.clearRect(0, 0, mapW, mapH);
      if (REDUCED) return; // static page for reduced motion
      for (const cl of clouds) {
        cl.x += cl.v;
        if (cl.x - cl.w > mapW) cl.x = -cl.w;             // wrap across the seam
        const base = (0.55 + 0.45 * Math.sin(t * cl.sp + cl.ph)) * 0.62 * cl.fade;
        if (base < 0.02) continue;
        for (const s of cl.sub) {
          const ox = s.ox + s.sa * Math.sin(t * s.sw + s.ph);
          const oy = s.oy + s.sb * Math.sin(t * s.sw * 1.37 + s.ph * 1.7);
          const rot = t * s.rs + s.ph;
          const sw = s.size, sh = sw * (sprites[s.spr].height / sprites[s.spr].width);
          const a = base * s.al * (0.7 + 0.3 * Math.sin(t * s.sw * 0.9 + s.ph));
          if (a < 0.02) continue;
          cctx.save();
          cctx.translate(cl.x + ox, cl.y + oy);
          cctx.rotate(rot);
          cctx.globalAlpha = Math.min(1, a);
          cctx.drawImage(sprites[s.spr], -sw / 2, -sh / 2, sw, sh);
          cctx.restore();
        }
      }
      cctx.globalAlpha = 1;
    }

    markersEl = document.createElement("div");
    markersEl.className = "map-markers";
    zoomEl.appendChild(markersEl);

    // ---- Tap ripple rings ---------------------------------------------------
    // In addition to the glyph spring, a tap spawns a visible expanding ring so
    // the splash reads clearly (the spring alone is subtle). The rings are DOM
    // nodes inside the zoom layer, so they pan/zoom with the map; a constant
    // on-screen size is kept with the same 1/--zoom counter-scale as markers.
    const ripplesEl = document.createElement("div");
    ripplesEl.className = "map-ripples";
    ripplesEl.setAttribute("aria-hidden", "true");
    zoomEl.appendChild(ripplesEl);
    function spawnRipple(px, py, size, color) {
      if (REDUCED) return;
      const el = document.createElement("span");
      el.className = "map-ripple";
      el.style.left = px + "px";
      el.style.top = py + "px";
      el.style.setProperty("--ripple-size", size + "px");
      el.style.borderColor = color || "rgba(198, 231, 253, 0.9)";
      el.addEventListener("animationend", () => el.remove());
      ripplesEl.appendChild(el);
    }

    // ---- Crosshair + live coordinate readout ------------------------------
    const cross = document.createElement("div");
    cross.className = "map-crosshair";
    cross.setAttribute("aria-hidden", "true");
    stage.appendChild(cross);
    const vline = document.createElement("i"); vline.className = "cross-v";
    const hline = document.createElement("i"); hline.className = "cross-h";
    cross.appendChild(vline); cross.appendChild(hline);

    const readout = document.createElement("div");
    readout.className = "map-readout";
    readout.setAttribute("aria-hidden", "true"); // decorative pointer readout; must not announce on every move
    const roCoords = document.createElement("span"); roCoords.className = "map-readout-coords";
    const roLand = document.createElement("span"); roLand.className = "map-readout-land";
    readout.appendChild(roCoords); readout.appendChild(roLand);
    stage.appendChild(readout);
    let readoutX = 0, readoutY = 0, readoutOn = false, readoutQueued = false;
    function queueReadout(x, y) {
      readoutX = x; readoutY = y; readoutOn = true;
      if (readoutQueued) return;
      readoutQueued = true;
      requestAnimationFrame(() => {
        readoutQueued = false;
        if (!readoutOn) return;
        // Coordinates come from the pointer's MAP position (true while zoomed/
        // panned); the chip is placed at the pointer's stage position on screen.
        const mpt = toMap(readoutX, readoutY);
        const lon = (mpt.x / CHARW / COLS) * 360 - 180;
        const lat = 90 - (mpt.y / LINEH / ROWS) * 180;
        const c = Math.floor(mpt.x / CHARW), r = Math.floor(mpt.y / LINEH);
        const inBounds = c >= 0 && c < COLS && r >= 0 && r < ROWS;
        const isLand = inBounds && kind[r * COLS + c];
        roCoords.textContent =
          Math.abs(lat).toFixed(1) + "° " + (lat >= 0 ? "N" : "S") +
          "  ·  " + Math.abs(lon).toFixed(1) + "° " + (lon >= 0 ? "E" : "W");
        roLand.textContent = isLand ? "land" : "ocean";
        roLand.dataset.state = isLand ? "land" : "ocean";
        cross.style.left = readoutX + "px";
        cross.style.top = readoutY + "px";
        cross.style.opacity = "1";
        readout.style.left = Math.min(readoutX + 14, mapW - 170) + "px";
        readout.style.top = Math.max(6, readoutY - 34) + "px";
        readout.style.opacity = "1";
      });
    }
    function hideReadout() {
      readoutOn = false;
      cross.style.opacity = "0";
      readout.style.opacity = "0";
    }

    // ---- Hover card --------------------------------------------------------
    const CARD_F = Math.max(11, Math.round(PX * 0.95));
    const cardFont = CARD_F + "px " + MONO;
    // Only the fallback path needs a probe canvas, so measure lazily.
    let cardChar = 0;
    function cardCharW() {
      if (!cardChar) {
        const probe2 = document.createElement("canvas").getContext("2d");
        probe2.font = cardFont;
        cardChar = probe2.measureText("MMMMMMMMMM").width / 10;
      }
      return cardChar;
    }

    card = document.createElement("div");
    card.className = "map-card";
    card.setAttribute("role", "tooltip");
    const cardCat = document.createElement("span"); cardCat.className = "map-card-cat";
    const cardName = document.createElement("span"); cardName.className = "map-card-name";
    const cardNative = document.createElement("span"); cardNative.className = "map-card-native";
    const cardLoc = document.createElement("span"); cardLoc.className = "map-card-loc";
    const cardTag = document.createElement("pre"); cardTag.className = "map-card-tag";
    const cardCoords = document.createElement("span"); cardCoords.className = "map-card-coords";
    const cardCta = document.createElement("span"); cardCta.className = "map-card-cta";
    cardCta.textContent = "Open field note →";
    card.appendChild(cardCat); card.appendChild(cardName); card.appendChild(cardNative);
    card.appendChild(cardLoc);
    card.appendChild(cardTag); card.appendChild(cardCoords); card.appendChild(cardCta);
    stage.appendChild(card);

    /* ---- A card that hugs its text ------------------------------------
       The card used to be a fixed 252px box in CSS while js/map.js positioned
       it against a CARD_W of 230 or 252 — the two disagreed on mobile, so the
       flip-to-the-other-side decision was made against the wrong width. Now
       the width is measured from the text and written from here; the CSS only
       caps it. Everything below is read from the live elements once, at build
       time, so the numbers cannot drift from the stylesheet. */
    const cardStyle = getComputedStyle(card);
    const CARD_CHROME =
      (parseFloat(cardStyle.paddingLeft) || 0) + (parseFloat(cardStyle.paddingRight) || 0) +
      (parseFloat(cardStyle.borderLeftWidth) || 0) + (parseFloat(cardStyle.borderRightWidth) || 0);
    const CSS_CARD_MAX = parseFloat(cardStyle.maxWidth) || 252;
    const CARD_MAX_W = isMobile
      ? Math.max(180, Math.min(CSS_CARD_MAX, Math.round(mapW * 0.62)))
      : CSS_CARD_MAX;
    const CARD_MIN_W = Math.min(CARD_MAX_W, 190);
    const CARD_TEXT_W = Math.max(40, CARD_MAX_W - CARD_CHROME);   // the widest the text may get
    const CARD_MIN_TEXT = Math.max(40, CARD_MIN_W - CARD_CHROME);
    let cardW = CARD_MAX_W, cardH = 200;

    // Canvas font string + tracking for one of the card's own elements, so a
    // line the site paints in Georgia is measured in Georgia.
    function elFont(el) {
      const s = getComputedStyle(el);
      const style = s.fontStyle && s.fontStyle !== "normal" ? s.fontStyle + " " : "";
      const weight = s.fontWeight && s.fontWeight !== "400" && s.fontWeight !== "normal"
        ? s.fontWeight + " " : "";
      const size = parseFloat(s.fontSize) || 12;
      return {
        font: style + weight + s.fontSize + " " + s.fontFamily,
        ls: parseFloat(s.letterSpacing) || 0,
        upper: s.textTransform === "uppercase",
        lh: parseFloat(s.lineHeight) || size * 1.2,
        mb: parseFloat(s.marginBottom) || 0,
        chrome:
          (parseFloat(s.paddingLeft) || 0) + (parseFloat(s.paddingRight) || 0) +
          (parseFloat(s.borderLeftWidth) || 0) + (parseFloat(s.borderRightWidth) || 0),
        chromeY:
          (parseFloat(s.paddingTop) || 0) + (parseFloat(s.paddingBottom) || 0) +
          (parseFloat(s.borderTopWidth) || 0) + (parseFloat(s.borderBottomWidth) || 0)
      };
    }
    const CARD_FONTS = {
      name: elFont(cardName), loc: elFont(cardLoc), coords: elFont(cardCoords),
      cta: elFont(cardCta), cat: elFont(cardCat), tag: elFont(cardTag),
      native: elFont(cardNative)
    };
    // Measured while it was still displayed; a place whose native name equals
    // its Latin one never shows it.
    cardNative.hidden = true;
    const CARD_CHROME_Y =
      (parseFloat(cardStyle.paddingTop) || 0) + (parseFloat(cardStyle.paddingBottom) || 0) +
      (parseFloat(cardStyle.borderTopWidth) || 0) + (parseFloat(cardStyle.borderBottomWidth) || 0);
    // How much width one of the card's own lines really wants: the widest line
    // it wraps to at the cap, never its unwrapped length. "Marble Caves
    // (Grottoes of General Carrera)" is 336px of Georgia on one line — asking
    // for that would pin every card to the cap and there would be nothing left
    // to shrink-wrap.
    const runPre = new Map();
    function runHandle(role, text) {
      const f = CARD_FONTS[role];
      const str = f.upper ? String(text).toUpperCase() : String(text);
      const key = role + "|" + str;
      let pre = runPre.get(key);
      if (!pre) {
        pre = prepareWithSegments(str, f.font, f.ls ? { letterSpacing: f.ls } : undefined);
        runPre.set(key, pre);
      }
      return { pre: pre, f: f, str: str };
    }
    function runWidth(role, text) {
      const h = runHandle(role, text);
      const room = Math.max(20, CARD_TEXT_W - h.f.chrome);
      // + ls: CSS paints a letter-space after the final grapheme too.
      return measureLineStats(h.pre, room).maxLineWidth + (h.str ? h.f.ls : 0) + h.f.chrome;
    }
    function runLines(role, text, textW) {
      const h = runHandle(role, text);
      return Math.max(1, measureLineStats(h.pre, Math.max(20, textW - h.f.chrome)).lineCount);
    }

    // Wrap the tagline through the shared text-metrics module so the hover
    // card measures with the same font-role registry as the rest of the site
    // (role "hover-card" == the .map-card-tag rule). If js/text.js is absent
    // or its `metrics` flag is off, fall back to the local pretext call.
    function tagLines(text, width) {
      const T = window.ATLAS_TEXT;
      if (T && typeof T.linesOfText === "function") {
        try {
          const viaModule = T.linesOfText("hover-card", text, width || CARD_TEXT_W);
          if (viaModule && viaModule.length) return trimEnds(viaModule);
        } catch (e) { /* fall through to the local path */ }
      }
      return trimEnds(wrapLines(text, cardFont, cardCharW(), 30, CARD_F * 1.3));
    }
    // .map-card-tag is `white-space: pre-wrap`, so a hanging trailing space
    // could push a full line over the edge and wrap it a second time.
    function trimEnds(lines) {
      return lines.map(function (l) { return l.replace(/\s+$/, ""); })
        .filter(function (l) { return l.length; });
    }
    // A last line holding one lonely word is the classic typographic widow.
    function isWidow(lines) {
      return lines.length >= 2 && !/\s/.test(lines[lines.length - 1].trim());
    }

    /* Shrink-wrap one tagline, then refuse to leave a one-word last line.
       tightWidthOfText() gives the narrowest box with the same line count;
       if that still ends on a single word, walk narrower (which pulls a word
       down onto the last line) and then wider, and keep the first width that
       reads properly. The chosen lines are baked into the <pre> with real
       newlines, so widening the card for a long name cannot re-wrap them. */
    const tagFits = new Map();
    function tagFit(p) {
      let fit = tagFits.get(p.id);
      if (fit) return fit;
      const T = window.ATLAS_TEXT;
      const text = String(p.tagline || "");
      if (!FLAGS.hoverFit || !T || typeof T.tightWidthOfText !== "function") {
        fit = { width: CARD_TEXT_W, lines: tagLines(text, CARD_TEXT_W) };
        tagFits.set(p.id, fit);
        return fit;
      }
      let width = T.tightWidthOfText("hover-card", text, CARD_TEXT_W);
      let lines = tagLines(text, width);
      if (isWidow(lines)) {
        const STEP = 3;
        let found = null;
        for (let w = width - STEP; w >= CARD_MIN_TEXT && !found; w -= STEP) {
          const candidate = tagLines(text, w);
          if (candidate.length > TAG_MAX_LINES + 1) break;   // do not grow it forever
          if (!isWidow(candidate)) found = { width: w, lines: candidate };
        }
        for (let w = width + STEP; w <= CARD_TEXT_W && !found; w += STEP) {
          const candidate = tagLines(text, w);
          if (!isWidow(candidate)) found = { width: w, lines: candidate };
        }
        if (found) { width = found.width; lines = found.lines; }
      }
      fit = { width: width, lines: lines };
      tagFits.set(p.id, fit);
      return fit;
    }

    /* ---- The native name inside the hover card ------------------------
       Measured through window.ATLAS_TEXT's "native-name" role — the same
       registry entry css/style.css paints `.map-card-native` from, and the
       one js/text.js prepared under the place's own locale. The line is left
       to wrap on its own (no baked newlines): pretext says how many lines the
       card must be tall for, and scripts/smoke.mjs checks that every break
       the browser then makes falls on an Intl.Segmenter word boundary. */
    const nativeFits = new Map();
    function nativeFit(p) {
      let fit = nativeFits.get(p.id);
      if (fit) return fit;
      const text = nativeTextFor(p);
      const f = CARD_FONTS.native;
      fit = {
        text: text, width: 0, dir: dirForLang(p.nativeLang),
        lang: p.nativeLang || "", wordBreak: "normal"
      };
      const T = window.ATLAS_TEXT;
      if (text && T && typeof T.tightWidthOfText === "function") {
        const room = Math.max(20, CARD_TEXT_W - f.chrome);
        try {
          fit.width = T.tightWidthOfText("native-name", text, room) + f.chrome;
          fit.dir = T.directionOf("native-name", p.id, p.nativeLang);
          const rec = T.localeFor("native-name", p.id);
          if (rec) fit.wordBreak = rec.wordBreak;
        } catch (e) { fit.width = 0; }
      }
      nativeFits.set(p.id, fit);
      return fit;
    }
    // How many lines the native name needs once the card's width is settled.
    function nativeLines(fit, textW) {
      if (!fit.text) return 0;
      const T = window.ATLAS_TEXT;
      const room = Math.max(20, textW - CARD_FONTS.native.chrome);
      if (T && typeof T.lineCountOfText === "function") {
        try { return Math.max(1, T.lineCountOfText("native-name", fit.text, room)); }
        catch (e) { return 1; }
      }
      return 1;
    }

    // Final card width: the widest thing it has to hold, capped by the CSS.
    // The height comes out of the same line counts, so positionCard() can keep
    // a tall card on screen without ever reading the DOM back.
    const cardFits = new Map();
    function cardFit(x) {
      let fitted = cardFits.get(x.p.id);
      if (fitted) return fitted;
      const p = x.p;
      const fit = tagFit(p);
      const native = nativeFit(p);
      const cat = catById.get(p.category);
      const loc = p.country + " — " + p.region;
      const coords = "≈ " + p.coordinates;
      const cta = cardCta.textContent;
      let textW = fit.width;
      if (FLAGS.hoverFit) {
        textW = Math.max(textW, runWidth("name", p.name));
        textW = Math.max(textW, native.width);
        textW = Math.max(textW, runWidth("loc", loc));
        textW = Math.max(textW, runWidth("coords", coords));
        textW = Math.max(textW, runWidth("cta", cta));
        if (cat) textW = Math.max(textW, runWidth("cat", cat.label));
        textW = Math.max(CARD_MIN_TEXT, Math.min(CARD_TEXT_W, textW));
      } else {
        textW = CARD_TEXT_W;
      }
      const F = CARD_FONTS;
      const nativeCount = nativeLines(native, textW);
      const height = CARD_CHROME_Y +
        (cat ? F.cat.lh + F.cat.chromeY + F.cat.mb : 0) +
        runLines("name", p.name, textW) * F.name.lh + F.name.mb +
        (nativeCount ? nativeCount * F.native.lh + F.native.mb : 0) +
        runLines("loc", loc, textW) * F.loc.lh + F.loc.mb +
        fit.lines.length * F.tag.lh + F.tag.mb +
        runLines("coords", coords, textW) * F.coords.lh + F.coords.mb +
        runLines("cta", cta, textW) * F.cta.lh;
      fitted = {
        width: Math.ceil(textW + CARD_CHROME),
        height: Math.ceil(height),
        lines: fit.lines,
        native: native,
        nativeLines: nativeCount
      };
      cardFits.set(x.p.id, fitted);
      return fitted;
    }

    function positionCard(x) {
      // The card is a child of the (untransformed) stage, so position it in
      // stage/screen px, not map px. The marker's on-screen spot is toStage(pos).
      // The flip and the clamp both use the card's real, measured width.
      const sp = toStage(x.pos.x, x.pos.y);
      const flip = sp.x > vpW - cardW - 40;
      const left = Math.max(6, Math.min(vpW - cardW - 6,
        flip ? sp.x - 16 - cardW : sp.x + 16));
      const top = Math.max(8, Math.min(Math.max(8, vpH - cardH - 8), sp.y - 60));
      card.style.left = left + "px";
      card.style.top = top + "px";
      card.dataset.side = flip ? "left" : "right";
    }
    function showCard(x) {
      if (cardVisibleId === x.p.id) { positionCard(x); return; }
      cardVisibleId = x.p.id;
      const cat = catById.get(x.p.category);
      const fit = cardFit(x);
      cardW = fit.width;
      cardH = fit.height;
      card.style.setProperty("width", cardW + "px");
      cardCat.textContent = cat ? cat.label : "";
      cardCat.style.color = x.accent;
      cardCat.style.borderColor = x.accent;
      cardName.textContent = x.p.name;
      const native = fit.native;
      if (native && native.text) {
        cardNative.hidden = false;
        cardNative.textContent = native.text;
        if (native.lang) cardNative.setAttribute("lang", native.lang);
        else cardNative.removeAttribute("lang");
        cardNative.setAttribute("dir", native.dir);
        if (native.wordBreak === "keep-all") cardNative.setAttribute("data-wb", "keep-all");
        else cardNative.removeAttribute("data-wb");
      } else {
        cardNative.hidden = true;
        cardNative.textContent = "";
      }
      cardLoc.textContent = x.p.country + " — " + x.p.region;
      cardTag.textContent = fit.lines.join("\n");
      cardCoords.textContent = "≈ " + x.p.coordinates;
      card.style.setProperty("--accent", x.accent);
      positionCard(x);
      card.classList.add("is-visible");
    }
    function hideCard() {
      cardVisibleId = null;
      card.classList.remove("is-visible");
    }
    function lightCard(id, on) {
      const el = document.querySelector('.card[data-place-id="' + id + '"]');
      if (el) el.classList.toggle("card--lit", on);
    }

    // ---- Markers (dots only — no text labels) ------------------------------
    markerRefs = []; // { id, el } for the current build; search dims the rest
    // Project every place to a map position first.
    for (const x of places) {
      const pos = project(x.p, COLS, ROWS, CHARW, LINEH);
      if (!pos) continue;
      x.pos = pos;
      x.dx = pos.x;
      x.dy = pos.y;
    }
    // Collision nudge: at small map sizes a few markers (e.g. the dense
    // SE-Asia cluster, or two Icelandic ice caves that project to the SAME grid
    // cell) can sit on top of each other. We push coincident pairs apart with a
    // stable pairwise relaxation — every pass re-measures the current positions
    // and displaces both members of a pair by half the deficit (no cascading),
    // with the total displacement capped so a dot can never be thrown across
    // the map. The TRUE coordinates (x.pos) are still used for the ripple and
    // the hover card, so a nudged dot still points at the right place.
    // (The old algorithm read already-nudged positions of later markers and
    // produced NaN for exact coincidences, which CSS drops — throwing the dot
    // to the map's top-left corner.)
    const MIN_SEP = Math.max(20, PX * 1.8);
    const MAX_DISP = 1.6 * LINEH;
    for (let pass = 0; pass < 10; pass++) {
      let any = false;
      for (let a = 0; a < places.length; a++) {
        const A = places[a];
        for (let b = a + 1; b < places.length; b++) {
          const B = places[b];
          let ddx = B.dx - A.dx, ddy = B.dy - A.dy;
          let d = Math.hypot(ddx, ddy);
          if (d >= MIN_SEP) continue;
          if (d < 0.01) { d = 0.01; ddx = 0; ddy = -1; } // exact coincidence: split vertically
          const push = (MIN_SEP - d) / 2;
          A.dx -= (ddx / d) * push; A.dy -= (ddy / d) * push;
          B.dx += (ddx / d) * push; B.dy += (ddy / d) * push;
          any = true;
        }
      }
      for (const x of places) {
        const ddx = x.dx - x.pos.x, ddy = x.dy - x.pos.y;
        const d = Math.hypot(ddx, ddy);
        if (d > MAX_DISP) { // keep the dot near its true position
          x.dx = x.pos.x + (ddx / d) * MAX_DISP;
          x.dy = x.pos.y + (ddy / d) * MAX_DISP;
        }
        x.dx = Math.max(8, Math.min(mapW - 8, x.dx));
        x.dy = Math.max(8, Math.min(mapH - 8, x.dy));
      }
      if (!any) break;
    }
    // The grid cell the dot actually sits in after the nudge. Labels anchor
    // off this (not off x.pos) so a nudged dot and its name stay together.
    for (const x of places) {
      if (!x.pos) continue;
      x.gcol = Math.max(0, Math.min(COLS - 1, Math.floor(x.dx / CHARW)));
      x.grow = Math.max(0, Math.min(ROWS - 1, Math.floor(x.dy / LINEH)));
    }
    // Build the marker buttons.
    for (const x of places) {
      if (!x.pos) continue;
      const p = x.p;
      const m = document.createElement("button");
      m.type = "button";
      m.className = "map-marker";
      m.style.left = x.dx + "px";
      m.style.top = x.dy + "px";
      m.style.color = x.accent;
      m.style.animationDelay = (Math.random() * 0.6).toFixed(2) + "s";
      m.setAttribute("data-place-id", p.id);
      m.setAttribute("aria-label", p.name + ", " + p.country + " — open field note");
      const ring = document.createElement("span"); ring.className = "map-marker-ring";
      const g = document.createElement("span"); g.className = "map-marker-glyph";
      m.appendChild(ring); m.appendChild(g);
      markersEl.appendChild(m);
      markerRefs.push({ id: p.id, el: m });

      const labelEl = () => {
        const entry = labelEls.get(p.id);
        return entry ? entry.el : null;
      };
      const enter = () => {
        showCard(x);
        lightCard(p.id, true);
        m.classList.add("is-hot");
        const le = labelEl();
        if (le) le.classList.add("is-hot");
        hoveredX = x;
        const tick = () => { if (hoveredX === x) stir(x.pos.col, x.pos.row, 0.85); };
        tick();
        if (hoverTimer) clearInterval(hoverTimer);
        hoverTimer = setInterval(tick, 260);
      };
      const leave = () => {
        if (hoveredX === x) hoveredX = null;
        if (hoverTimer) { clearInterval(hoverTimer); hoverTimer = null; }
        hideCard();
        lightCard(p.id, false);
        m.classList.remove("is-hot");
        const le = labelEl();
        if (le) le.classList.remove("is-hot");
      };
      // The name label hovers like its dot (js/map.js's label layer calls
      // these), and both light the same grid card.
      x.enter = enter;
      x.leave = leave;
      m.addEventListener("mouseenter", enter);
      m.addEventListener("mouseleave", leave);
      m.addEventListener("focus", enter);
      m.addEventListener("blur", leave);
      // One click always opens the info card (previously the first click only
      // dismissed the hover card that mouseenter had shown, so it felt like two
      // clicks were needed).
      m.addEventListener("click", (e) => {
        e.stopPropagation();
        hideCard();
        if (location.hash !== "#/place/" + encodeURIComponent(p.id)) {
          location.hash = "#/place/" + encodeURIComponent(p.id);
        }
      });
    }
    showCardRef = showCard;
    hideCardRef = hideCard;
    cardNativeLinesRef = function (x) {
      const fit = cardFit(x);
      return fit.nativeLines || 0;
    };
    applyView();
    requestPlacement();   // ocean names at tier 0, place names from 1.4×

    // ---- Pulse a marker when its place is opened from the grid/dialog (#4) ----
    window.addEventListener("atlas:highlight", (e) => {
      const id = e.detail;
      const ref = markerRefs.find((r) => r.id === id);
      if (!ref) return;
      ref.el.classList.add("is-pulsing");
      clearTimeout(ref.pulseT);
      ref.pulseT = setTimeout(() => ref.el.classList.remove("is-pulsing"), 1600);
    });

    // ---- "You are here" marker + nearest wonder (#3) -----------------------
    // app.js runs geolocation and dispatches this. We drop a pulsing marker at
    // the visitor's true position and, if a wonder is close by, label it with
    // the distance. The marker is a child of the zoom layer so it pans/zooms
    // with the map; we reposition it on view changes.
    let userMarker = null, userLabel = null, userLoc = null;
    function placeUserMarker() {
      if (!userLoc || !userMarker) return;
      const col = ((userLoc.lon + 180) / 360) * COLS;
      const row = ((90 - userLoc.lat) / 180) * ROWS;
      const x = (col + 0.5) * CHARW;
      const y = (row + 0.5) * LINEH;
      userMarker.style.left = x + "px";
      userMarker.style.top = y + "px";
      if (userLabel) {
        userLabel.style.left = x + "px";
        userLabel.style.top = y + "px";
      }
    }
    window.addEventListener("atlas:locate", (e) => {
      const { lat, lon } = e.detail;
      userLoc = { lat, lon };
      if (!userMarker) {
        userMarker = document.createElement("div");
        userMarker.className = "map-user";
        userMarker.setAttribute("aria-hidden", "true");
        const dot = document.createElement("span"); dot.className = "map-user-dot";
        const ring = document.createElement("span"); ring.className = "map-user-ring";
        userMarker.appendChild(ring); userMarker.appendChild(dot);
        zoomEl.appendChild(userMarker);
        userLabel = document.createElement("div");
        userLabel.className = "map-user-label";
        userLabel.setAttribute("aria-hidden", "true");
        zoomEl.appendChild(userLabel);
      }
      // Nearest wonder (within the full dataset, so the label is always useful).
      let best = null, bestD = Infinity;
      for (const p of DATA.places) {
        const c = parseCoords(p.coordinates);
        if (!c) continue;
        const d = distKm({ lat, lon }, c);
        if (d < bestD) { bestD = d; best = p; }
      }
      if (best) {
        userLabel.textContent = "You are here · nearest: " + best.name + " (" + fmtKm(bestD) + ")";
        userLabel.classList.add("is-visible");
      }
      placeUserMarker();
      // If reduced motion, keep it static (no CSS animation is fine).
    });
    window.addEventListener("atlas:locate-error", () => {
      if (userLabel) {
        userLabel.textContent = "Couldn't get your location — allow it and try again";
        userLabel.classList.add("is-visible", "is-error");
      }
    });

    // ---- Pointer interaction with the sea ----------------------------------
    let rect = { left: 0, top: 0 };
    const drag = { active: false, moved: false, startX: 0, startY: 0, lastX: 0, lastY: 0 };
    const refreshRect = () => {
      const r = stage.getBoundingClientRect();
      rect = { left: r.left, top: r.top };
    };
    refreshRect();
    window.addEventListener("scroll", refreshRect, { passive: true, once: false });

    // Pan: drag on the stage (pointer events cover mouse + touch).
    stage.addEventListener("pointermove", (e) => {
      if (!drag.active) return;
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      if (!drag.moved && (Math.abs(sx - drag.startX) > 4 || Math.abs(sy - drag.startY) > 4)) {
        drag.moved = true;
      }
      if (drag.moved) {
        panX += sx - drag.lastX;
        panY += sy - drag.lastY;
        drag.lastX = sx; drag.lastY = sy;
        clampPan();
        applyView();
      }
    });
    stage.addEventListener("wheel", (e) => {
      if (REDUCED) return;
      e.preventDefault();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      zoomTo(view.zoom * (e.deltaY < 0 ? 1.15 : 1 / 1.15), sx, sy);
    }, { passive: false });
    // Keyboard zoom for accessibility (buttons are also on the viewport).
    stage.tabIndex = 0;
    stage.addEventListener("keydown", (e) => {
      if (e.key === "+" || e.key === "=") zoomTo(view.zoom * 1.2, vpW / 2, vpH / 2);
      else if (e.key === "-" || e.key === "_") zoomTo(view.zoom / 1.2, vpW / 2, vpH / 2);
      else if (e.key === "0") { view.zoom = 1; panX = 0; panY = 0; applyView(); }
    });

    stage.addEventListener("mousemove", (e) => {
      refreshRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      const mpt = toMap(sx, sy);
      if (mpt.x < 0 || mpt.y < 0 || mpt.x > mapW || mpt.y > mapH) { hideReadout(); return; }
      stir(Math.floor(mpt.x / CHARW), Math.floor(mpt.y / LINEH), 0.34);
      queueReadout(sx, sy);
    });
    stage.addEventListener("mouseleave", hideReadout);
    stage.addEventListener("pointerdown", (e) => {
      refreshRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      // A press can become a pan; the tap-splash fires on pointerup if it
      // didn't move. (Pointer events, not mouse: pointerup always fires,
      // even when the button is released outside the stage.)
      drag.startX = sx; drag.startY = sy;
      drag.lastX = sx; drag.lastY = sy;
      drag.active = true; drag.moved = false;
    });
    window.addEventListener("pointerup", (e) => {
      const wasTap = drag.active && !drag.moved;
      drag.active = false;
      if (!wasTap) return;
      // Mouse-only tap splash here; touch splashes in touchstart (touch fires
      // both, so don't double up).
      if (e.pointerType !== "mouse") return;
      refreshRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      const mpt = toMap(sx, sy);
      if (mpt.x < 0 || mpt.y < 0 || mpt.x > mapW || mpt.y > mapH) return;
      const c = Math.floor(mpt.x / CHARW), r = Math.floor(mpt.y / LINEH);
      // A big central splash plus a surrounding ring, so the tap reads as a
      // visible expanding ripple rather than a single flickering glyph.
      stir(c, r, 4.2);
      stir(c - 1, r, 2.2); stir(c + 1, r, 2.2);
      stir(c, r - 1, 2.2); stir(c, r + 1, 2.2);
      stir(c - 2, r, 1.3); stir(c + 2, r, 1.3);
      stir(c, r - 2, 1.3); stir(c, r + 2, 1.3);
      // Visible expanding ring on a water tap.
      if (!kind[r * COLS + c]) spawnRipple(mpt.x, mpt.y, 96);
    });
    // Touch: tap water to splash.
    stage.addEventListener("touchstart", (e) => {
      const t = e.touches[0];
      if (!t) return;
      refreshRect();
      const sx = t.clientX - rect.left;
      const sy = t.clientY - rect.top;
      const mpt = toMap(sx, sy);
      if (mpt.x < 0 || mpt.y < 0 || mpt.x > mapW || mpt.y > mapH) return;
      const c = Math.floor(mpt.x / CHARW), r = Math.floor(mpt.y / LINEH);
      if (!kind[r * COLS + c]) {
        // Big tap-splash on touch too (water only; land splashes its shore ring).
        stir(c, r, 3.8);
        stir(c - 1, r, 1.8); stir(c + 1, r, 1.8);
        stir(c, r - 1, 1.8); stir(c, r + 1, 1.8);
        stir(c - 2, r, 1.1); stir(c + 2, r, 1.1);
        stir(c, r - 2, 1.1); stir(c, r + 2, 1.1);
        spawnRipple(mpt.x, mpt.y, 96);
      }
    }, { passive: true });
    // Tap empty sea also dismisses an open card (but a pan shouldn't).
    stage.addEventListener("click", (e) => {
      if (drag.moved) return;
      if (e.target === base || e.target === sea) hideCard();
    });

    ambientTimer = setInterval(() => {
      const i = waterCells[(Math.random() * waterCells.length) | 0];
      disp[i] += 0.75;
      if (Math.random() < 0.5) {
        const j = waterCells[(Math.random() * waterCells.length) | 0];
        disp[j] += 0.55;
      }
    }, 900);

    // ---- Animation loop ------------------------------------------------------
    // The sea canvas carries a wave field: three superposed traveling wave
    // trains (a long eastward swell, a slow westward set, and a fast short
    // chop) blended with the interactive ripple spring. Each water cell's
    // value maps through a glyph + luminance ramp so wave crests read as thin
    // bright lines moving across the water and calm troughs stay faint.
    // The clock resets on resume-from-off-screen so the waves continue smoothly
    // instead of jumping.
    waveT0 = performance.now();
    // Ambient wave strength (kept modest so ripples still read clearly).
    const WAVE_AMP = REDUCED ? 0.0 : 0.8;
    // Wave trains: [angular freq (rad/s), col wavenumber, row wavenumber].
    // Directions differ per train so the crests interfere and never repeat.
    const W1 = { w: 0.30, kc: 0.11, kr: 0.020, amp: 0.55 }; // long eastward swell
    const W2 = { w: 0.42, kc: -0.05, kr: 0.070, amp: 0.40 }; // slow westward set
    const W3 = { w: 1.05, kc: 0.05, kr: 0.030, amp: 0.30 };  // fast short chop
    function frame(now) {
      const t = (now - waveT0) / 1000;
      if (!viewportVisible) { loopRunning = false; return; } // off-screen: suspended
      // Spring step for the interactive ripple field.
      for (let i = 0; i < COLS * ROWS; i++) {
        const n = nCount[i];
        if (!n) continue;
        let lap = 0;
        const b4 = i * 4;
        for (let k = 0; k < n; k++) lap += disp[neighbors[b4 + k]];
        vel[i] += (lap - n * disp[i]) * SPREAD;
      }
      for (let i = 0; i < COLS * ROWS; i++) {
        if (!nCount[i]) continue;
        vel[i] += -SPRING * disp[i];
        vel[i] *= DAMP;
        disp[i] += vel[i];
      }

      sctx.clearRect(0, 0, mapW, mapH);
      const N = waterLen;
      for (let w = 0; w < N; w++) {
        const i = waterList[w];
        const c = i % COLS, r = (i / COLS) | 0;
        let density;
        if (WAVE_AMP > 0) {
          // Superposed traveling waves; the per-region phase tilt makes the
          // fronts arrive at different times so the sea shimmers rather than
          // scrolling. Normalized to 0..1, then gamma-sharpened into crests.
          const ph = phase[i];
          const a = Math.sin(t * W1.w + c * W1.kc + r * W1.kr + ph);
          const b = Math.sin(t * W2.w + c * W2.kc + r * W2.kr - ph * 0.4);
          const e = Math.sin(t * W3.w + c * W3.kc + r * W3.kr);
          let m = a * W1.amp + b * W2.amp + e * W3.amp;   // ~ -1.25 .. 1.25
          const base = (m + 1.25) / 2.5;                   // 0 .. 1
          // Gamma concentrates energy into moving crests; a regional bias
          // keeps some seas consistently rougher than others.
          density = Math.pow(base, WAVE_GAMMA) * WAVE_AMP
            + 0.10 * (waveBias[i] - 0.5);
        } else {
          density = 0.05;
        }
        // Interactive ripple: crests light up and lift, troughs dim. Added
        // after gamma so a splash punches through the ambient waves.
        const d = disp[i];
        const densityRaw = density + d * 1.5;
        const y0 = (r + 0.5) * LINEH;
        const y = y0 + Math.max(-2.4, Math.min(2.4, d)) * LIFT;
        if (densityRaw <= 0.08) continue;            // static floor shows through
        const lvl = Math.max(1, Math.min(5, (densityRaw * 6) | 0));
        sctx.fillStyle = OCEAN_COLORS[lvl];
        sctx.fillText(OCEAN_GLYPHS[lvl], c * CHARW, y);
        // Troughs dip below the baseline in a dimmer tone, so a splash has a
        // visible leading and trailing edge, not just a bright crest.
        if (d < -0.5) {
          sctx.fillStyle = "rgba(20, 40, 70, 0.55)";
          sctx.fillText("·", c * CHARW, y);
        }
      }
      // Drifting white clouds on top of the waves (fades out over Antarctica).
      drawClouds(t);
      animId = requestAnimationFrame(frame);
    }
    frameRef = frame;
    startLoop();
    lastPX = PX;
  }

  // ---- Legend (persistent) ----------------------------------------------------
  const legend = $("atlas-legend");
  if (legend) {
    for (const c of DATA.categories) {
      const n = DATA.places.filter((p) => p.category === c.id).length;
      const el = document.createElement("span");
      el.className = "legend-item";
      el.style.setProperty("--chip-accent", c.accent);
      const dot = document.createElement("i"); dot.className = "legend-dot";
      const t = document.createElement("span");
      t.textContent = c.label + " " + n;
      el.appendChild(dot); el.appendChild(t);
      legend.appendChild(el);
    }
  }

  // ---- Search / filter sync -------------------------------------------------
  // app.js dispatches "atlas:visible" (detail: Set of visible place ids)
  // whenever the grid is filtered. Non-matching markers dim + de-emphasize so
  // the hero map responds to the search box, not just the grid below.
  function setMarkersVisible(ids) {
    visibleIds = ids || null;
    // A filtered-out dot must not keep its name in the sea, and the cells it
    // gives up are then free for its neighbours — so re-route.
    requestPlacement();
    for (const ref of markerRefs) {
      const on = ids == null || ids.has(ref.id);
      ref.el.classList.toggle("is-dimmed", !on);
      ref.el.setAttribute("aria-hidden", String(!on));
      if (!on) ref.el.tabIndex = -1;
      else if (ref.el.tabIndex === -1) ref.el.removeAttribute("tabindex");
    }
    // A dimmed marker being hovered should release its card.
    if (ids != null && cardVisibleId && !ids.has(cardVisibleId)) hideCard();
  }
  window.addEventListener("atlas:visible", (e) => setMarkersVisible(e.detail));
  // Initial state in case the app rendered before this module's first build.
  setMarkersVisible(null);

  // ---- Initial build + responsive rebuild ------------------------------------
  // Build after first layout so the viewport has its final size, then rebuild
  // whenever the computed cell size actually changes (window resize, container
  // reflow). Waves reset on rebuild — intentional, it's a splash.
  let lastPX = 0;
  function scheduleBuild() {
    const px = computePX();
    if (Math.abs(px - lastPX) > 0.25) build();
  }
  requestAnimationFrame(() => {
    build();
    if (typeof ResizeObserver !== "undefined") {
      new ResizeObserver(scheduleBuild).observe(viewport);
    }
    let t = null;
    window.addEventListener("resize", () => {
      clearTimeout(t);
      t = setTimeout(scheduleBuild, 150);
    });

    // ---- Off-screen pause (#1) -------------------------------------------
    // Stop the animation loop and ambient ripples when the map scrolls out of
    // view, resume when it comes back. The wave clock is wall-clock based, so
    // the sea continues exactly where it left off (no jump on resume). Saves
    // CPU for the rest of the page.
    if (typeof IntersectionObserver === "function") {
      new IntersectionObserver((entries) => {
        const visible = entries.some((en) => en.isIntersecting);
        viewportVisible = visible;
        if (visible) {
          if (!frameRef) return;
          if (REDUCED) return; // static map: nothing to restart
          if (ambientTimer === null) {
            ambientTimer = setInterval(() => {
              const i = waterCells[(Math.random() * waterCells.length) | 0];
              disp[i] += 0.75;
              if (Math.random() < 0.5) {
                const j = waterCells[(Math.random() * waterCells.length) | 0];
                disp[j] += 0.55;
              }
            }, 900);
          }
          startLoop();
        } else {
          if (animId) cancelAnimationFrame(animId);
          loopRunning = false; // so startLoop() can restart when visible again
          if (ambientTimer) { clearInterval(ambientTimer); ambientTimer = null; }
        }
      }, { threshold: 0.02 }).observe(viewport);
    }

    // ---- Map controls: zoom in/out, reset (#16). The "Locate me" button is
    // owned by app.js (it runs geolocation); map.js only reacts to its events.
    const zin = $("map-zoom-in");
    const zout = $("map-zoom-out");
    const zreset = $("map-zoom-reset");
    if (zin) zin.addEventListener("click", () => { vpW = viewport.clientWidth || vpW; vpH = viewport.clientHeight || vpH; zoomTo(view.zoom * 1.3, vpW / 2, vpH / 2); });
    if (zout) zout.addEventListener("click", () => { vpW = viewport.clientWidth || vpW; vpH = viewport.clientHeight || vpH; zoomTo(view.zoom / 1.3, vpW / 2, vpH / 2); });
    if (zreset) zreset.addEventListener("click", () => { view.zoom = 1; panX = 0; panY = 0; vpW = viewport.clientWidth || vpW; vpH = viewport.clientHeight || vpH; applyView(); });
  });
})();
