/* Text Atlas — a full-screen, country-colored character-grid world map with
   a living, ripple-driven text sea. Sized to fill the viewport; rebuilt on
   resize. Data comes from js/landmap.js (generated by scripts/build-map.mjs
   from Natural Earth 110m country polygons):
     - Land: per-cell palette color (country hue × dither step) + texture glyph
     - Sea:  spring simulation over water cells; stirred by pointer move/tap,
       marker hovers, and ambient pulses; rendered as reactive glyphs.
     - Markers: colored dots (no text labels); hover/focus/tap shows a
       pretext-wrapped hover card and lights the matching grid card.
   CSP-safe: same-origin module import, no eval, textContent for all data. */
import { prepareWithSegments, layoutWithLines } from "../vendor/pretext/layout.js";

(function () {
  "use strict";

  const DATA = window.ATLAS_DATA || { categories: [], places: [] };
  const MAPS = window.LANDMAPS;
  const catById = new Map(DATA.categories.map((c) => [c.id, c]));
  const $ = (id) => document.getElementById(id);

  const section = $("text-atlas");
  const viewport = section && section.querySelector(".map-viewport");
  if (!section || !viewport || !DATA.places.length) return;

  const isMobile = (typeof window.matchMedia === "function") &&
    window.matchMedia("(max-width: 640px)").matches;
  const PALETTE = (MAPS && MAPS.palette) || null;
  const MAP = (MAPS && (isMobile ? MAPS.mobile : MAPS.desktop)) || null;
  if (!MAP || !PALETTE || !MAP.glyphs || !MAP.glyphs.length) return;

  const COLS = MAP.cols;
  const ROWS = MAP.rows;

  const MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, 'DejaVu Sans Mono', monospace";
  const DPR = Math.min(2, (typeof devicePixelRatio === "number" ? devicePixelRatio : 1) || 1);
  const ROW_FACTOR = 1.18;
  const PX_MAX = 18;
  // Mobile floor is low so the whole grid fits the content width — at 8px a
  // 96-col grid would be ~770px and get clipped on a phone.
  const PX_MIN = isMobile ? 4 : 8;
  // SPRING/DAMP/SPREAD/LIFT tune the interactive ripple field. SPREAD how fast
  // a splash's ring travels outward, DAMP how long it lasts (lower = longer),
  // LIFT how far crests visually bob the glyphs.
  const SPRING = 0.022, DAMP = 0.94, SPREAD = 0.22, LIFT = 5;

  // Wave-like ocean: three superposed traveling wave trains (a long eastward
  // swell, a slow westward set, and a fast short chop) with per-region front
  // tilt, rendered through a glyph + luminance ramp. Wave crests are
  // gamma-sharpened so they read as thin bright lines moving across the water
  // instead of a static smoke texture; the ripple spring on top carries
  // pointer splashes.
  const OCEAN_GLYPHS = ["·", "·", ":", "~", "≈", "≈"];
  const OCEAN_COLORS = [
    "rgba(74, 124, 164, 0.10)",
    "rgba(90, 146, 186, 0.17)",
    "rgba(110, 172, 208, 0.26)",
    "rgba(140, 200, 232, 0.38)",
    "rgba(176, 226, 248, 0.52)",
    "rgba(214, 244, 255, 0.70)"
  ];
  const WAVE_GAMMA = 1.9;          // >1 → quiet floor, thin bright crests
  // Clouds are withheld from Antarctica (it is already white ice): the fade
  // ramps 1 → 0 over the last few rows so a cloud dissolves into the ice.
  function cloudFade(row) {
    const startRow = ROWS - 5;
    if (row < startRow) return 1;
    return Math.max(0, 1 - (row - startRow) / 4);
  }
  const REDUCED = (typeof matchMedia === "function") &&
    matchMedia("(prefers-reduced-motion: reduce)").matches;

  // Monospace advance per px of font size (measured from the font engine).
  const _p = document.createElement("canvas").getContext("2d");
  _p.font = "100px " + MONO;
  const UNIT = _p.measureText("MMMMMMMMMM").width / 10 / 100;

  // Reflow-free wrapping via pretext (monospace grid ⇒ chars = cells).
  function wrapLines(text, font, maxCharsPx, maxChars, lineHeight) {
    text = String(text).trim();
    if (maxChars <= 0) return [text];
    if (text.length <= maxChars) return [text];
    try {
      const pre = prepareWithSegments(text, font);
      const res = layoutWithLines(pre, maxChars * maxCharsPx, lineHeight);
      if (res && res.lines && res.lines.length) {
        return res.lines.map((l) => l.text).filter((t) => t.length);
      }
    } catch (e) { /* fall back below */ }
    const words = text.split(/\s+/);
    const lines = [];
    let cur = "";
    for (const w of words) {
      if (!cur) cur = w;
      else if ((cur + " " + w).length <= maxChars) cur += " " + w;
      else { lines.push(cur); cur = w; }
    }
    if (cur) lines.push(cur);
    return lines;
  }

  function parseCoords(s) {
    const m = /(-?\d+(?:\.\d+)?)\s*°?\s*([NSns])[\s,]+(-?\d+(?:\.\d+)?)\s*°?\s*([EWew])/.exec(s || "");
    if (!m) return null;
    return { lat: m[1] * (m[2].toUpperCase() === "S" ? -1 : 1), lon: m[3] * (m[4].toUpperCase() === "W" ? -1 : 1) };
  }
  function project(p, cols, rows, charW, lineH) {
    const c = parseCoords(p.coordinates);
    if (!c) return null;
    const col = Math.max(0, Math.min(cols - 1, Math.round(((c.lon + 180) / 360) * cols)));
    const row = Math.max(0, Math.min(rows - 1, Math.round(((90 - c.lat) / 180) * rows)));
    return { col, row, x: (col + 0.5) * charW, y: (row + 0.5) * lineH };
  }
  // Great-circle distance (km) between two lat/lon pairs.
  function distKm(a, b) {
    const R = 6371, rad = Math.PI / 180;
    const dLat = (b.lat - a.lat) * rad, dLon = (b.lon - a.lon) * rad;
    const s = Math.sin(dLat / 2) ** 2 + Math.cos(a.lat * rad) * Math.cos(b.lat * rad) * Math.sin(dLon / 2) ** 2;
    return 2 * R * Math.asin(Math.min(1, Math.sqrt(s)));
  }
  const fmtKm = (km) => km < 1000 ? Math.round(km) + " km" : (km / 1000).toFixed(1) + "k km";

  // Cell kind: 0 = water, 1 = land (color = palette index).
  const kind = new Uint8Array(COLS * ROWS);
  const cellColor = new Uint8Array(COLS * ROWS);
  const cellGlyph = new Uint8Array(COLS * ROWS);
  for (let r = 0; r < ROWS; r++) {
    const gRow = MAP.glyphs[r], cRow = MAP.colors[r];
    for (let c = 0; c < COLS; c++) {
      const i = r * COLS + c;
      if (cRow[c] !== " ") {
        kind[i] = 1;
        cellColor[i] = cRow.charCodeAt(c) - 65; // 'A' → 0
        cellGlyph[i] = gRow.charCodeAt(c);
      }
    }
  }

  // Neighbour lists for the water-cell spring simulation.
  const neighbors = new Int32Array(COLS * ROWS * 4);
  const nCount = new Uint8Array(COLS * ROWS);
  for (let r = 0; r < ROWS; r++) {
    for (let c = 0; c < COLS; c++) {
      const i = r * COLS + c;
      if (kind[i]) continue;
      let n = 0;
      if (c > 0 && !kind[i - 1]) neighbors[i * 4 + n++] = i - 1;
      if (c < COLS - 1 && !kind[i + 1]) neighbors[i * 4 + n++] = i + 1;
      if (r > 0 && !kind[i - COLS]) neighbors[i * 4 + n++] = i - COLS;
      if (r < ROWS - 1 && !kind[i + COLS]) neighbors[i * 4 + n++] = i + COLS;
      nCount[i] = n;
    }
  }
  const waterCells = [];
  for (let i = 0; i < COLS * ROWS; i++) if (!kind[i]) waterCells.push(i);

  const places = DATA.places
    .map((p) => ({ p, accent: (catById.get(p.category) || {}).accent || "#e8b45a" }))
    .filter((x) => parseCoords(x.p.coordinates));

  // ---- Mutable per-build state -------------------------------------------
  let PX, LINEH, CHARW, mapW, mapH;
  let disp, vel, animId = 0, ambientTimer = null, hoverTimer = null, hoveredX = null;
  let stage, card, cardVisibleId = null;
  // Off-screen pause: when the map scrolls out of view we stop the animation
  // loop and ambient timer (they otherwise run for the page's whole life).
  let viewportVisible = true, waveT0 = 0, frameRef = null, loopRunning = false;
  // Pan/zoom view. The map content lives in a `.map-zoom` wrapper (sized mapW×mapH)
  // that we scale about its centre and translate in screen px. The stage itself
  // stays untransformed (just centred) so pointer→map math stays exact.
  let view, panX, panY, zoomEl, vpW = 0, vpH = 0;
  const ZOOM_MIN = 1, ZOOM_MAX = 4;
  function clamp(v, a, b) { return Math.max(a, Math.min(b, v)); }
  // Pointer (stage-local sx,sy) → map-local px,py under the current view.
  function toMap(sx, sy) {
    return {
      x: (sx - mapW / 2 - panX) / view.zoom + mapW / 2,
      y: (sy - mapH / 2 - panY) / view.zoom + mapH / 2
    };
  }
  // Map-local → stage-local (where non-scaling UI like the card/crosshair live).
  function toStage(px, py) {
    return {
      x: (px - mapW / 2) * view.zoom + panX + mapW / 2,
      y: (py - mapH / 2) * view.zoom + panY + mapH / 2
    };
  }
  function clampPan() {
    const overX = Math.max(0, (mapW * view.zoom - vpW) / 2);
    const overY = Math.max(0, (mapH * view.zoom - vpH) / 2);
    panX = clamp(panX, -overX, overX);
    panY = clamp(panY, -overY, overY);
  }
  // Start the animation loop if it isn't already running (the off-screen
  // observer and the first build can both want to start it).
  function startLoop() {
    if (!frameRef || loopRunning) return;
    loopRunning = true;
    animId = requestAnimationFrame(frameRef);
  }
  function applyView() {
    if (!zoomEl) return;
    zoomEl.style.transform = "translate(" + panX + "px, " + panY + "px) scale(" + view.zoom + ")";
    // Counter-scale so markers keep a constant on-screen size at any zoom
    // (CSS uses 1 / var(--zoom) for marker dimensions).
    zoomEl.style.setProperty("--zoom", String(view.zoom));
  }
  // Zoom so that the map point under stage-local (sx,sy) stays fixed there.
  function zoomTo(newZoom, sx, sy) {
    const z1 = clamp(newZoom, ZOOM_MIN, ZOOM_MAX);
    const p = toMap(sx, sy);
    view.zoom = z1;
    panX = sx - mapW / 2 - (p.x - mapW / 2) * z1;
    panY = sy - mapH / 2 - (p.y - mapH / 2) * z1;
    clampPan();
    applyView();
  }
  // Wave phase + per-region bias (computed at build so the ocean has a stable
  // regional character; the time-varying sines in frame() make it travel).
  let phase, waveBias, waterList, waterLen = 0;
  // Marker elements for the currently built map (reset each build). Search
  // and category filtering dim the ones that don't match, so the map mirrors
  // the grid instead of always showing every dot.
  let markerRefs = [];

  function computePX() {
    const vw = viewport.clientWidth || 1200;
    const vh = viewport.clientHeight || 700;
    const px = Math.min(vw / (COLS * UNIT), vh / (ROWS * ROW_FACTOR));
    return Math.max(PX_MIN, Math.min(PX_MAX, px));
  }

  function clearBuild() {
    if (animId) cancelAnimationFrame(animId);
    if (ambientTimer) { clearInterval(ambientTimer); ambientTimer = null; }
    if (hoverTimer) { clearInterval(hoverTimer); hoverTimer = null; }
    if (stage) stage.remove();
    stage = null; card = null; cardVisibleId = null; hoveredX = null;
    zoomEl = null;
    loopRunning = false;
    if (view) { view.zoom = 1; }
    panX = 0; panY = 0;
  }

  function build() {
    clearBuild();
    PX = computePX();
    LINEH = PX * ROW_FACTOR;
    const probe = document.createElement("canvas").getContext("2d");
    probe.font = PX + "px " + MONO;
    CHARW = probe.measureText("MMMMMMMMMM").width / 10;
    mapW = COLS * CHARW;
    mapH = ROWS * LINEH;
    const FONT = PX + "px " + MONO;
    view = { zoom: 1 };
    panX = 0; panY = 0;
    vpW = viewport.clientWidth || mapW;
    vpH = viewport.clientHeight || mapH;

    disp = new Float32Array(COLS * ROWS);
    vel = new Float32Array(COLS * ROWS);

    // Wave phase + regional bias. Phase tilts wave fronts slightly per region
    // so swell arrives at different places at different times (real seas
    // interfere rather than scroll uniformly); bias gives each region a
    // characterful base energy (some seas are just rougher).
    phase = new Float32Array(COLS * ROWS);
    waveBias = new Float32Array(COLS * ROWS);
    waterList = waterCells;
    waterLen = waterCells.length;
    for (let i = 0; i < COLS * ROWS; i++) {
      if (kind[i]) continue;
      const c = i % COLS, r = (i / COLS) | 0;
      phase[i] = c * 0.21 + r * 0.09;
      waveBias[i] = 0.5 + 0.5 * Math.sin(c * 0.11 + r * 0.17); // 0..1
    }

    function stir(c, r, amp) {
      c = Math.round(c); r = Math.round(r);
      if (c < 0 || c >= COLS || r < 0 || r >= ROWS) return;
      const i = r * COLS + c;
      if (!kind[i]) { disp[i] += amp; return; }
      // Land tapped: ripple the nearest water ring instead.
      for (let rad = 1; rad <= 8; rad++) {
        for (let dr = -rad; dr <= rad; dr++) {
          for (let dc = -rad; dc <= rad; dc++) {
            if (Math.max(Math.abs(dr), Math.abs(dc)) !== rad) continue;
            const rr = r + dr, cc = c + dc;
            if (rr < 0 || rr >= ROWS || cc < 0 || cc >= COLS) continue;
            const j = rr * COLS + cc;
            if (!kind[j]) { disp[j] += amp * 0.6; return; }
          }
        }
      }
    }

    // ---- Stage ----------------------------------------------------------
    stage = document.createElement("div");
    stage.className = "map-stage";
    stage.style.width = mapW + "px";
    stage.style.height = mapH + "px";
    stage.style.fontFamily = MONO;
    stage.style.fontSize = PX + "px";
    stage.style.lineHeight = LINEH + "px";
    viewport.appendChild(stage);

    // All the visual layers (base, sea, clouds, markers) live inside this
    // wrapper so pan/zoom can transform them as one unit. The crosshair,
    // readout and hover card stay on the stage (untransformed) so they keep a
    // constant on-screen size regardless of zoom.
    zoomEl = document.createElement("div");
    zoomEl.className = "map-zoom";
    zoomEl.style.width = mapW + "px";
    zoomEl.style.height = mapH + "px";
    stage.appendChild(zoomEl);

    // ---- Base canvas: static land + faint sea floor (drawn once) ------------
    // The animated water (traveling waves + ripples) lives on the sea canvas
    // canvas above this; keeping the base static makes each frame cheap.
    const base = document.createElement("canvas");
    base.width = Math.round(mapW * DPR);
    base.height = Math.round(mapH * DPR);
    base.className = "map-base";
    base.style.width = mapW + "px";
    base.style.height = mapH + "px";
    zoomEl.appendChild(base);
    const bctx = base.getContext("2d");
    bctx.scale(DPR, DPR);
    bctx.font = FONT;
    bctx.textBaseline = "middle";
    bctx.textAlign = "left";
    for (let r = 0; r < ROWS; r++) {
      const rowBase = r * COLS;
      const y = (r + 0.5) * LINEH;
      for (let c = 0; c < COLS; c++) {
        const i = rowBase + c;
        const x = c * CHARW;
        if (kind[i]) {
          bctx.fillStyle = PALETTE[cellColor[i]];
          bctx.fillText(String.fromCharCode(cellGlyph[i]), x, y);
        } else {
          bctx.fillStyle = "rgba(80, 130, 170, 0.10)";
          bctx.fillText("·", x, y);
        }
      }
    }

    const sea = document.createElement("canvas");
    sea.width = Math.round(mapW * DPR);
    sea.height = Math.round(mapH * DPR);
    sea.className = "map-sea";
    sea.style.width = mapW + "px";
    sea.style.height = mapH + "px";
    zoomEl.appendChild(sea);
    const sctx = sea.getContext("2d");
    sctx.scale(DPR, DPR);
    sctx.font = FONT;
    sctx.textBaseline = "middle";
    sctx.textAlign = "left";

    // ---- Cloud layer --------------------------------------------------------
    // A handful of drifting white clouds crossing the map (land and sea).
    // Each cloud is a cluster of 3..5 independently wobbling, slowly rotating
    // sub-puffs, so the silhouette morphs continuously (less blocky than a
    // single stamped sprite). Each cloud fades out near the pole — the
    // Antarctica rows are already white ice, so the fade makes the white
    // dissolve into the white instead of reading as an opaque band. The
    // canvas sits above the sea and below the markers so a dot stays visible
    // when a cloud passes.
    const cloudsEl = document.createElement("canvas");
    cloudsEl.width = Math.round(mapW);   // 1x is plenty for soft blobs
    cloudsEl.height = Math.round(mapH);
    cloudsEl.className = "map-sea";      // reuse the absolute-position style
    cloudsEl.style.width = mapW + "px";
    cloudsEl.style.height = mapH + "px";
    zoomEl.appendChild(cloudsEl);
    const cctx = cloudsEl.getContext("2d");

    const CLOUD_N = isMobile ? 4 : 6;
    // Pre-render several soft, lumpy cloud sprites (random radial-gradient
    // lobes). Several distinct shapes plus per-cloud sub-puff clusters keep
    // the outline from looking like a repeating blocky blob.
    function makeCloudSprite() {
      const W = 360, H = 200;
      const cv = document.createElement("canvas");
      cv.width = W; cv.height = H;
      const sc = cv.getContext("2d");
      const n = 5 + ((Math.random() * 3) | 0); // 5..7 lobes
      for (let l = 0; l < n; l++) {
        const bx = 0.20 + Math.random() * 0.60;
        const by = 0.26 + Math.random() * 0.48;
        const br = (0.15 + Math.random() * 0.20) * W;
        const g = sc.createRadialGradient(bx * W, by * H, 0, bx * W, by * H, br);
        g.addColorStop(0, "rgba(248, 251, 254, 0.92)");
        g.addColorStop(0.45, "rgba(242, 247, 252, 0.42)");
        g.addColorStop(1, "rgba(238, 245, 252, 0)");
        sc.fillStyle = g;
        sc.fillRect(0, 0, W, H);
      }
      return cv;
    }
    const sprites = [makeCloudSprite(), makeCloudSprite(), makeCloudSprite()];
    const clouds = [];
    for (let k = 0; k < CLOUD_N; k++) {
      const wPx = (0.18 + Math.random() * 0.16) * mapW;   // cloud footprint
      const hPx = wPx * 0.5;
      const cy = (0.08 + Math.random() * 0.55) * mapH;    // stays clear of the white polar strip
      const nSub = 3 + ((Math.random() * 3) | 0);         // 3..5 sub-puffs
      const sub = [];
      for (let s = 0; s < nSub; s++) {
        sub.push({
          spr: (Math.random() * sprites.length) | 0,
          ox: (Math.random() - 0.5) * 0.9 * wPx,           // rest offset from center
          oy: (Math.random() - 0.5) * 0.7 * hPx,
          sw: 0.06 + Math.random() * 0.10,                // wobble speed
          sa: (0.15 + Math.random() * 0.20) * wPx,        // wobble amplitude (x)
          sb: (0.10 + Math.random() * 0.18) * hPx,        // wobble amplitude (y)
          ph: Math.random() * 6.283,
          size: (0.5 + Math.random() * 0.55) * wPx,       // sub-puff sprite width
          rs: -0.5 + Math.random(),                        // rad/s slow rotation
          al: 0.28 + Math.random() * 0.24                 // sub-puff alpha
        });
      }
      clouds.push({
        x: Math.random() * mapW,
        y: cy, w: wPx, h: hPx,
        v: 0.22 + Math.random() * 0.22,                   // px/frame, west→east
        ph: Math.random() * 6.283,
        sp: 0.05 + Math.random() * 0.06,
        sub
      });
    }
    // Per-cloud Antarctic fade from each sub-puff's rest row.
    for (const cl of clouds) {
      let f = 1;
      for (const s of cl.sub) f = Math.min(f, cloudFade((cl.y + s.oy) / LINEH));
      cl.fade = f;
    }
    function drawClouds(t) {
      cctx.clearRect(0, 0, mapW, mapH);
      if (REDUCED) return; // static page for reduced motion
      for (const cl of clouds) {
        cl.x += cl.v;
        if (cl.x - cl.w > mapW) cl.x = -cl.w;             // wrap across the seam
        const base = (0.55 + 0.45 * Math.sin(t * cl.sp + cl.ph)) * 0.62 * cl.fade;
        if (base < 0.02) continue;
        for (const s of cl.sub) {
          const ox = s.ox + s.sa * Math.sin(t * s.sw + s.ph);
          const oy = s.oy + s.sb * Math.sin(t * s.sw * 1.37 + s.ph * 1.7);
          const rot = t * s.rs + s.ph;
          const sw = s.size, sh = sw * (sprites[s.spr].height / sprites[s.spr].width);
          const a = base * s.al * (0.7 + 0.3 * Math.sin(t * s.sw * 0.9 + s.ph));
          if (a < 0.02) continue;
          cctx.save();
          cctx.translate(cl.x + ox, cl.y + oy);
          cctx.rotate(rot);
          cctx.globalAlpha = Math.min(1, a);
          cctx.drawImage(sprites[s.spr], -sw / 2, -sh / 2, sw, sh);
          cctx.restore();
        }
      }
      cctx.globalAlpha = 1;
    }

    const markersEl = document.createElement("div");
    markersEl.className = "map-markers";
    zoomEl.appendChild(markersEl);

    // ---- Tap ripple rings ---------------------------------------------------
    // In addition to the glyph spring, a tap spawns a visible expanding ring so
    // the splash reads clearly (the spring alone is subtle). The rings are DOM
    // nodes inside the zoom layer, so they pan/zoom with the map; a constant
    // on-screen size is kept with the same 1/--zoom counter-scale as markers.
    const ripplesEl = document.createElement("div");
    ripplesEl.className = "map-ripples";
    ripplesEl.setAttribute("aria-hidden", "true");
    zoomEl.appendChild(ripplesEl);
    function spawnRipple(px, py, size, color) {
      if (REDUCED) return;
      const el = document.createElement("span");
      el.className = "map-ripple";
      el.style.left = px + "px";
      el.style.top = py + "px";
      el.style.setProperty("--ripple-size", size + "px");
      el.style.borderColor = color || "rgba(198, 231, 253, 0.9)";
      el.addEventListener("animationend", () => el.remove());
      ripplesEl.appendChild(el);
    }

    // ---- Crosshair + live coordinate readout ------------------------------
    const cross = document.createElement("div");
    cross.className = "map-crosshair";
    cross.setAttribute("aria-hidden", "true");
    stage.appendChild(cross);
    const vline = document.createElement("i"); vline.className = "cross-v";
    const hline = document.createElement("i"); hline.className = "cross-h";
    cross.appendChild(vline); cross.appendChild(hline);

    const readout = document.createElement("div");
    readout.className = "map-readout";
    readout.setAttribute("aria-hidden", "true"); // decorative pointer readout; must not announce on every move
    const roCoords = document.createElement("span"); roCoords.className = "map-readout-coords";
    const roLand = document.createElement("span"); roLand.className = "map-readout-land";
    readout.appendChild(roCoords); readout.appendChild(roLand);
    stage.appendChild(readout);
    let readoutX = 0, readoutY = 0, readoutOn = false, readoutQueued = false;
    function queueReadout(x, y) {
      readoutX = x; readoutY = y; readoutOn = true;
      if (readoutQueued) return;
      readoutQueued = true;
      requestAnimationFrame(() => {
        readoutQueued = false;
        if (!readoutOn) return;
        // Coordinates come from the pointer's MAP position (true while zoomed/
        // panned); the chip is placed at the pointer's stage position on screen.
        const mpt = toMap(readoutX, readoutY);
        const lon = (mpt.x / CHARW / COLS) * 360 - 180;
        const lat = 90 - (mpt.y / LINEH / ROWS) * 180;
        const c = Math.floor(mpt.x / CHARW), r = Math.floor(mpt.y / LINEH);
        const inBounds = c >= 0 && c < COLS && r >= 0 && r < ROWS;
        const isLand = inBounds && kind[r * COLS + c];
        roCoords.textContent =
          Math.abs(lat).toFixed(1) + "° " + (lat >= 0 ? "N" : "S") +
          "  ·  " + Math.abs(lon).toFixed(1) + "° " + (lon >= 0 ? "E" : "W");
        roLand.textContent = isLand ? "land" : "ocean";
        roLand.dataset.state = isLand ? "land" : "ocean";
        cross.style.left = readoutX + "px";
        cross.style.top = readoutY + "px";
        cross.style.opacity = "1";
        readout.style.left = Math.min(readoutX + 14, mapW - 170) + "px";
        readout.style.top = Math.max(6, readoutY - 34) + "px";
        readout.style.opacity = "1";
      });
    }
    function hideReadout() {
      readoutOn = false;
      cross.style.opacity = "0";
      readout.style.opacity = "0";
    }

    // ---- Hover card --------------------------------------------------------
    const CARD_F = Math.max(11, Math.round(PX * 0.95));
    const cardFont = CARD_F + "px " + MONO;
    const cardProbe = document.createElement("canvas").getContext("2d");
    cardProbe.font = cardFont;
    const CARD_CHAR = cardProbe.measureText("MMMMMMMMMM").width / 10;

    card = document.createElement("div");
    card.className = "map-card";
    card.setAttribute("role", "tooltip");
    const cardCat = document.createElement("span"); cardCat.className = "map-card-cat";
    const cardName = document.createElement("span"); cardName.className = "map-card-name";
    const cardLoc = document.createElement("span"); cardLoc.className = "map-card-loc";
    const cardTag = document.createElement("pre"); cardTag.className = "map-card-tag";
    const cardCoords = document.createElement("span"); cardCoords.className = "map-card-coords";
    const cardCta = document.createElement("span"); cardCta.className = "map-card-cta";
    cardCta.textContent = "Open field note →";
    card.appendChild(cardCat); card.appendChild(cardName); card.appendChild(cardLoc);
    card.appendChild(cardTag); card.appendChild(cardCoords); card.appendChild(cardCta);
    stage.appendChild(card);
    const CARD_W = isMobile ? Math.min(230, Math.round(mapW * 0.62)) : 252;

    function positionCard(x) {
      // The card is a child of the (untransformed) stage, so position it in
      // stage/screen px, not map px. The marker's on-screen spot is toStage(pos).
      const sp = toStage(x.pos.x, x.pos.y);
      const flip = sp.x > vpW - CARD_W - 40;
      const left = Math.max(6, Math.min(vpW - CARD_W - 6,
        flip ? sp.x - 16 - CARD_W : sp.x + 16));
      const top = Math.max(8, Math.min(Math.max(8, vpH - 200), sp.y - 60));
      card.style.left = left + "px";
      card.style.top = top + "px";
      card.dataset.side = flip ? "left" : "right";
    }
    function showCard(x) {
      if (cardVisibleId === x.p.id) { positionCard(x); return; }
      cardVisibleId = x.p.id;
      const cat = catById.get(x.p.category);
      cardCat.textContent = cat ? cat.label : "";
      cardCat.style.color = x.accent;
      cardCat.style.borderColor = x.accent;
      cardName.textContent = x.p.name;
      cardLoc.textContent = x.p.country + " — " + x.p.region;
      cardTag.textContent = wrapLines(x.p.tagline, cardFont, CARD_CHAR, 30, CARD_F * 1.3).join("\n");
      cardCoords.textContent = "≈ " + x.p.coordinates;
      card.style.setProperty("--accent", x.accent);
      positionCard(x);
      card.classList.add("is-visible");
    }
    function hideCard() {
      cardVisibleId = null;
      card.classList.remove("is-visible");
    }
    function lightCard(id, on) {
      const el = document.querySelector('.card[data-place-id="' + id + '"]');
      if (el) el.classList.toggle("card--lit", on);
    }

    // ---- Markers (dots only — no text labels) ------------------------------
    markerRefs = []; // { id, el } for the current build; search dims the rest
    // Project every place to a map position first.
    for (const x of places) {
      const pos = project(x.p, COLS, ROWS, CHARW, LINEH);
      if (!pos) continue;
      x.pos = pos;
      x.dx = pos.x;
      x.dy = pos.y;
    }
    // Collision nudge: at small map sizes a few markers (e.g. the dense
    // SE-Asia cluster, or two Icelandic ice caves that project to the SAME grid
    // cell) can sit on top of each other. We push coincident pairs apart with a
    // stable pairwise relaxation — every pass re-measures the current positions
    // and displaces both members of a pair by half the deficit (no cascading),
    // with the total displacement capped so a dot can never be thrown across
    // the map. The TRUE coordinates (x.pos) are still used for the ripple and
    // the hover card, so a nudged dot still points at the right place.
    // (The old algorithm read already-nudged positions of later markers and
    // produced NaN for exact coincidences, which CSS drops — throwing the dot
    // to the map's top-left corner.)
    const MIN_SEP = Math.max(20, PX * 1.8);
    const MAX_DISP = 1.6 * LINEH;
    for (let pass = 0; pass < 10; pass++) {
      let any = false;
      for (let a = 0; a < places.length; a++) {
        const A = places[a];
        for (let b = a + 1; b < places.length; b++) {
          const B = places[b];
          let ddx = B.dx - A.dx, ddy = B.dy - A.dy;
          let d = Math.hypot(ddx, ddy);
          if (d >= MIN_SEP) continue;
          if (d < 0.01) { d = 0.01; ddx = 0; ddy = -1; } // exact coincidence: split vertically
          const push = (MIN_SEP - d) / 2;
          A.dx -= (ddx / d) * push; A.dy -= (ddy / d) * push;
          B.dx += (ddx / d) * push; B.dy += (ddy / d) * push;
          any = true;
        }
      }
      for (const x of places) {
        const ddx = x.dx - x.pos.x, ddy = x.dy - x.pos.y;
        const d = Math.hypot(ddx, ddy);
        if (d > MAX_DISP) { // keep the dot near its true position
          x.dx = x.pos.x + (ddx / d) * MAX_DISP;
          x.dy = x.pos.y + (ddy / d) * MAX_DISP;
        }
        x.dx = Math.max(8, Math.min(mapW - 8, x.dx));
        x.dy = Math.max(8, Math.min(mapH - 8, x.dy));
      }
      if (!any) break;
    }
    // Build the marker buttons.
    for (const x of places) {
      if (!x.pos) continue;
      const p = x.p;
      const m = document.createElement("button");
      m.type = "button";
      m.className = "map-marker";
      m.style.left = x.dx + "px";
      m.style.top = x.dy + "px";
      m.style.color = x.accent;
      m.style.animationDelay = (Math.random() * 0.6).toFixed(2) + "s";
      m.setAttribute("data-place-id", p.id);
      m.setAttribute("aria-label", p.name + ", " + p.country + " — open field note");
      const ring = document.createElement("span"); ring.className = "map-marker-ring";
      const g = document.createElement("span"); g.className = "map-marker-glyph";
      m.appendChild(ring); m.appendChild(g);
      markersEl.appendChild(m);
      markerRefs.push({ id: p.id, el: m });

      const enter = () => {
        showCard(x);
        lightCard(p.id, true);
        m.classList.add("is-hot");
        hoveredX = x;
        const tick = () => { if (hoveredX === x) stir(x.pos.col, x.pos.row, 0.85); };
        tick();
        if (hoverTimer) clearInterval(hoverTimer);
        hoverTimer = setInterval(tick, 260);
      };
      const leave = () => {
        if (hoveredX === x) hoveredX = null;
        if (hoverTimer) { clearInterval(hoverTimer); hoverTimer = null; }
        hideCard();
        lightCard(p.id, false);
        m.classList.remove("is-hot");
      };
      m.addEventListener("mouseenter", enter);
      m.addEventListener("mouseleave", leave);
      m.addEventListener("focus", enter);
      m.addEventListener("blur", leave);
      // One click always opens the info card (previously the first click only
      // dismissed the hover card that mouseenter had shown, so it felt like two
      // clicks were needed).
      m.addEventListener("click", (e) => {
        e.stopPropagation();
        hideCard();
        if (location.hash !== "#/place/" + encodeURIComponent(p.id)) {
          location.hash = "#/place/" + encodeURIComponent(p.id);
        }
      });
    }
    applyView();

    // ---- Pulse a marker when its place is opened from the grid/dialog (#4) ----
    window.addEventListener("atlas:highlight", (e) => {
      const id = e.detail;
      const ref = markerRefs.find((r) => r.id === id);
      if (!ref) return;
      ref.el.classList.add("is-pulsing");
      clearTimeout(ref.pulseT);
      ref.pulseT = setTimeout(() => ref.el.classList.remove("is-pulsing"), 1600);
    });

    // ---- "You are here" marker + nearest wonder (#3) -----------------------
    // app.js runs geolocation and dispatches this. We drop a pulsing marker at
    // the visitor's true position and, if a wonder is close by, label it with
    // the distance. The marker is a child of the zoom layer so it pans/zooms
    // with the map; we reposition it on view changes.
    let userMarker = null, userLabel = null, userLoc = null;
    function placeUserMarker() {
      if (!userLoc || !userMarker) return;
      const col = ((userLoc.lon + 180) / 360) * COLS;
      const row = ((90 - userLoc.lat) / 180) * ROWS;
      const x = (col + 0.5) * CHARW;
      const y = (row + 0.5) * LINEH;
      userMarker.style.left = x + "px";
      userMarker.style.top = y + "px";
      if (userLabel) {
        userLabel.style.left = x + "px";
        userLabel.style.top = y + "px";
      }
    }
    window.addEventListener("atlas:locate", (e) => {
      const { lat, lon } = e.detail;
      userLoc = { lat, lon };
      if (!userMarker) {
        userMarker = document.createElement("div");
        userMarker.className = "map-user";
        userMarker.setAttribute("aria-hidden", "true");
        const dot = document.createElement("span"); dot.className = "map-user-dot";
        const ring = document.createElement("span"); ring.className = "map-user-ring";
        userMarker.appendChild(ring); userMarker.appendChild(dot);
        zoomEl.appendChild(userMarker);
        userLabel = document.createElement("div");
        userLabel.className = "map-user-label";
        userLabel.setAttribute("aria-hidden", "true");
        zoomEl.appendChild(userLabel);
      }
      // Nearest wonder (within the full dataset, so the label is always useful).
      let best = null, bestD = Infinity;
      for (const p of DATA.places) {
        const c = parseCoords(p.coordinates);
        if (!c) continue;
        const d = distKm({ lat, lon }, c);
        if (d < bestD) { bestD = d; best = p; }
      }
      if (best) {
        userLabel.textContent = "You are here · nearest: " + best.name + " (" + fmtKm(bestD) + ")";
        userLabel.classList.add("is-visible");
      }
      placeUserMarker();
      // If reduced motion, keep it static (no CSS animation is fine).
    });
    window.addEventListener("atlas:locate-error", () => {
      if (userLabel) {
        userLabel.textContent = "Couldn't get your location — allow it and try again";
        userLabel.classList.add("is-visible", "is-error");
      }
    });

    // ---- Pointer interaction with the sea ----------------------------------
    let rect = { left: 0, top: 0 };
    const drag = { active: false, moved: false, startX: 0, startY: 0, lastX: 0, lastY: 0 };
    const refreshRect = () => {
      const r = stage.getBoundingClientRect();
      rect = { left: r.left, top: r.top };
    };
    refreshRect();
    window.addEventListener("scroll", refreshRect, { passive: true, once: false });

    // Pan: drag on the stage (pointer events cover mouse + touch).
    stage.addEventListener("pointermove", (e) => {
      if (!drag.active) return;
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      if (!drag.moved && (Math.abs(sx - drag.startX) > 4 || Math.abs(sy - drag.startY) > 4)) {
        drag.moved = true;
      }
      if (drag.moved) {
        panX += sx - drag.lastX;
        panY += sy - drag.lastY;
        drag.lastX = sx; drag.lastY = sy;
        clampPan();
        applyView();
      }
    });
    stage.addEventListener("wheel", (e) => {
      if (REDUCED) return;
      e.preventDefault();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      zoomTo(view.zoom * (e.deltaY < 0 ? 1.15 : 1 / 1.15), sx, sy);
    }, { passive: false });
    // Keyboard zoom for accessibility (buttons are also on the viewport).
    stage.tabIndex = 0;
    stage.addEventListener("keydown", (e) => {
      if (e.key === "+" || e.key === "=") zoomTo(view.zoom * 1.2, vpW / 2, vpH / 2);
      else if (e.key === "-" || e.key === "_") zoomTo(view.zoom / 1.2, vpW / 2, vpH / 2);
      else if (e.key === "0") { view.zoom = 1; panX = 0; panY = 0; applyView(); }
    });

    stage.addEventListener("mousemove", (e) => {
      refreshRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      const mpt = toMap(sx, sy);
      if (mpt.x < 0 || mpt.y < 0 || mpt.x > mapW || mpt.y > mapH) { hideReadout(); return; }
      stir(Math.floor(mpt.x / CHARW), Math.floor(mpt.y / LINEH), 0.34);
      queueReadout(sx, sy);
    });
    stage.addEventListener("mouseleave", hideReadout);
    stage.addEventListener("pointerdown", (e) => {
      refreshRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      // A press can become a pan; the tap-splash fires on pointerup if it
      // didn't move. (Pointer events, not mouse: pointerup always fires,
      // even when the button is released outside the stage.)
      drag.startX = sx; drag.startY = sy;
      drag.lastX = sx; drag.lastY = sy;
      drag.active = true; drag.moved = false;
    });
    window.addEventListener("pointerup", (e) => {
      const wasTap = drag.active && !drag.moved;
      drag.active = false;
      if (!wasTap) return;
      // Mouse-only tap splash here; touch splashes in touchstart (touch fires
      // both, so don't double up).
      if (e.pointerType !== "mouse") return;
      refreshRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      const mpt = toMap(sx, sy);
      if (mpt.x < 0 || mpt.y < 0 || mpt.x > mapW || mpt.y > mapH) return;
      const c = Math.floor(mpt.x / CHARW), r = Math.floor(mpt.y / LINEH);
      // A big central splash plus a surrounding ring, so the tap reads as a
      // visible expanding ripple rather than a single flickering glyph.
      stir(c, r, 4.2);
      stir(c - 1, r, 2.2); stir(c + 1, r, 2.2);
      stir(c, r - 1, 2.2); stir(c, r + 1, 2.2);
      stir(c - 2, r, 1.3); stir(c + 2, r, 1.3);
      stir(c, r - 2, 1.3); stir(c, r + 2, 1.3);
      // Visible expanding ring on a water tap.
      if (!kind[r * COLS + c]) spawnRipple(mpt.x, mpt.y, 96);
    });
    // Touch: tap water to splash.
    stage.addEventListener("touchstart", (e) => {
      const t = e.touches[0];
      if (!t) return;
      refreshRect();
      const sx = t.clientX - rect.left;
      const sy = t.clientY - rect.top;
      const mpt = toMap(sx, sy);
      if (mpt.x < 0 || mpt.y < 0 || mpt.x > mapW || mpt.y > mapH) return;
      const c = Math.floor(mpt.x / CHARW), r = Math.floor(mpt.y / LINEH);
      if (!kind[r * COLS + c]) {
        // Big tap-splash on touch too (water only; land splashes its shore ring).
        stir(c, r, 3.8);
        stir(c - 1, r, 1.8); stir(c + 1, r, 1.8);
        stir(c, r - 1, 1.8); stir(c, r + 1, 1.8);
        stir(c - 2, r, 1.1); stir(c + 2, r, 1.1);
        stir(c, r - 2, 1.1); stir(c, r + 2, 1.1);
        spawnRipple(mpt.x, mpt.y, 96);
      }
    }, { passive: true });
    // Tap empty sea also dismisses an open card (but a pan shouldn't).
    stage.addEventListener("click", (e) => {
      if (drag.moved) return;
      if (e.target === base || e.target === sea) hideCard();
    });

    ambientTimer = setInterval(() => {
      const i = waterCells[(Math.random() * waterCells.length) | 0];
      disp[i] += 0.75;
      if (Math.random() < 0.5) {
        const j = waterCells[(Math.random() * waterCells.length) | 0];
        disp[j] += 0.55;
      }
    }, 900);

    // ---- Animation loop ------------------------------------------------------
    // The sea canvas carries a wave field: three superposed traveling wave
    // trains (a long eastward swell, a slow westward set, and a fast short
    // chop) blended with the interactive ripple spring. Each water cell's
    // value maps through a glyph + luminance ramp so wave crests read as thin
    // bright lines moving across the water and calm troughs stay faint.
    // The clock resets on resume-from-off-screen so the waves continue smoothly
    // instead of jumping.
    waveT0 = performance.now();
    // Ambient wave strength (kept modest so ripples still read clearly).
    const WAVE_AMP = REDUCED ? 0.0 : 0.8;
    // Wave trains: [angular freq (rad/s), col wavenumber, row wavenumber].
    // Directions differ per train so the crests interfere and never repeat.
    const W1 = { w: 0.30, kc: 0.11, kr: 0.020, amp: 0.55 }; // long eastward swell
    const W2 = { w: 0.42, kc: -0.05, kr: 0.070, amp: 0.40 }; // slow westward set
    const W3 = { w: 1.05, kc: 0.05, kr: 0.030, amp: 0.30 };  // fast short chop
    function frame(now) {
      const t = (now - waveT0) / 1000;
      if (!viewportVisible) { loopRunning = false; return; } // off-screen: suspended
      // Spring step for the interactive ripple field.
      for (let i = 0; i < COLS * ROWS; i++) {
        const n = nCount[i];
        if (!n) continue;
        let lap = 0;
        const b4 = i * 4;
        for (let k = 0; k < n; k++) lap += disp[neighbors[b4 + k]];
        vel[i] += (lap - n * disp[i]) * SPREAD;
      }
      for (let i = 0; i < COLS * ROWS; i++) {
        if (!nCount[i]) continue;
        vel[i] += -SPRING * disp[i];
        vel[i] *= DAMP;
        disp[i] += vel[i];
      }

      sctx.clearRect(0, 0, mapW, mapH);
      const N = waterLen;
      for (let w = 0; w < N; w++) {
        const i = waterList[w];
        const c = i % COLS, r = (i / COLS) | 0;
        let density;
        if (WAVE_AMP > 0) {
          // Superposed traveling waves; the per-region phase tilt makes the
          // fronts arrive at different times so the sea shimmers rather than
          // scrolling. Normalized to 0..1, then gamma-sharpened into crests.
          const ph = phase[i];
          const a = Math.sin(t * W1.w + c * W1.kc + r * W1.kr + ph);
          const b = Math.sin(t * W2.w + c * W2.kc + r * W2.kr - ph * 0.4);
          const e = Math.sin(t * W3.w + c * W3.kc + r * W3.kr);
          let m = a * W1.amp + b * W2.amp + e * W3.amp;   // ~ -1.25 .. 1.25
          const base = (m + 1.25) / 2.5;                   // 0 .. 1
          // Gamma concentrates energy into moving crests; a regional bias
          // keeps some seas consistently rougher than others.
          density = Math.pow(base, WAVE_GAMMA) * WAVE_AMP
            + 0.10 * (waveBias[i] - 0.5);
        } else {
          density = 0.05;
        }
        // Interactive ripple: crests light up and lift, troughs dim. Added
        // after gamma so a splash punches through the ambient waves.
        const d = disp[i];
        const densityRaw = density + d * 1.5;
        const y0 = (r + 0.5) * LINEH;
        const y = y0 + Math.max(-2.4, Math.min(2.4, d)) * LIFT;
        if (densityRaw <= 0.08) continue;            // static floor shows through
        const lvl = Math.max(1, Math.min(5, (densityRaw * 6) | 0));
        sctx.fillStyle = OCEAN_COLORS[lvl];
        sctx.fillText(OCEAN_GLYPHS[lvl], c * CHARW, y);
        // Troughs dip below the baseline in a dimmer tone, so a splash has a
        // visible leading and trailing edge, not just a bright crest.
        if (d < -0.5) {
          sctx.fillStyle = "rgba(20, 40, 70, 0.55)";
          sctx.fillText("·", c * CHARW, y);
        }
      }
      // Drifting white clouds on top of the waves (fades out over Antarctica).
      drawClouds(t);
      animId = requestAnimationFrame(frame);
    }
    frameRef = frame;
    startLoop();
    lastPX = PX;
  }

  // ---- Legend (persistent) ----------------------------------------------------
  const legend = $("atlas-legend");
  if (legend) {
    for (const c of DATA.categories) {
      const n = DATA.places.filter((p) => p.category === c.id).length;
      const el = document.createElement("span");
      el.className = "legend-item";
      el.style.setProperty("--chip-accent", c.accent);
      const dot = document.createElement("i"); dot.className = "legend-dot";
      const t = document.createElement("span");
      t.textContent = c.label + " " + n;
      el.appendChild(dot); el.appendChild(t);
      legend.appendChild(el);
    }
  }

  // ---- Search / filter sync -------------------------------------------------
  // app.js dispatches "atlas:visible" (detail: Set of visible place ids)
  // whenever the grid is filtered. Non-matching markers dim + de-emphasize so
  // the hero map responds to the search box, not just the grid below.
  function setMarkersVisible(ids) {
    for (const ref of markerRefs) {
      const on = ids == null || ids.has(ref.id);
      ref.el.classList.toggle("is-dimmed", !on);
      ref.el.setAttribute("aria-hidden", String(!on));
      if (!on) ref.el.tabIndex = -1;
      else if (ref.el.tabIndex === -1) ref.el.removeAttribute("tabindex");
    }
    // A dimmed marker being hovered should release its card.
    if (ids != null && cardVisibleId && !ids.has(cardVisibleId)) hideCard();
  }
  window.addEventListener("atlas:visible", (e) => setMarkersVisible(e.detail));
  // Initial state in case the app rendered before this module's first build.
  setMarkersVisible(null);

  // ---- Initial build + responsive rebuild ------------------------------------
  // Build after first layout so the viewport has its final size, then rebuild
  // whenever the computed cell size actually changes (window resize, container
  // reflow). Waves reset on rebuild — intentional, it's a splash.
  let lastPX = 0;
  function scheduleBuild() {
    const px = computePX();
    if (Math.abs(px - lastPX) > 0.25) build();
  }
  requestAnimationFrame(() => {
    build();
    if (typeof ResizeObserver !== "undefined") {
      new ResizeObserver(scheduleBuild).observe(viewport);
    }
    let t = null;
    window.addEventListener("resize", () => {
      clearTimeout(t);
      t = setTimeout(scheduleBuild, 150);
    });

    // ---- Off-screen pause (#1) -------------------------------------------
    // Stop the animation loop and ambient ripples when the map scrolls out of
    // view, resume when it comes back. The wave clock is wall-clock based, so
    // the sea continues exactly where it left off (no jump on resume). Saves
    // CPU for the rest of the page.
    if (typeof IntersectionObserver === "function") {
      new IntersectionObserver((entries) => {
        const visible = entries.some((en) => en.isIntersecting);
        viewportVisible = visible;
        if (visible) {
          if (!frameRef) return;
          if (REDUCED) return; // static map: nothing to restart
          if (ambientTimer === null) {
            ambientTimer = setInterval(() => {
              const i = waterCells[(Math.random() * waterCells.length) | 0];
              disp[i] += 0.75;
              if (Math.random() < 0.5) {
                const j = waterCells[(Math.random() * waterCells.length) | 0];
                disp[j] += 0.55;
              }
            }, 900);
          }
          startLoop();
        } else {
          if (animId) cancelAnimationFrame(animId);
          loopRunning = false; // so startLoop() can restart when visible again
          if (ambientTimer) { clearInterval(ambientTimer); ambientTimer = null; }
        }
      }, { threshold: 0.02 }).observe(viewport);
    }

    // ---- Map controls: zoom in/out, reset (#16). The "Locate me" button is
    // owned by app.js (it runs geolocation); map.js only reacts to its events.
    const zin = $("map-zoom-in");
    const zout = $("map-zoom-out");
    const zreset = $("map-zoom-reset");
    if (zin) zin.addEventListener("click", () => { vpW = viewport.clientWidth || vpW; vpH = viewport.clientHeight || vpH; zoomTo(view.zoom * 1.3, vpW / 2, vpH / 2); });
    if (zout) zout.addEventListener("click", () => { vpW = viewport.clientWidth || vpW; vpH = viewport.clientHeight || vpH; zoomTo(view.zoom / 1.3, vpW / 2, vpH / 2); });
    if (zreset) zreset.addEventListener("click", () => { view.zoom = 1; panX = 0; panY = 0; vpW = viewport.clientWidth || vpW; vpH = viewport.clientHeight || vpH; applyView(); });
  });
})();
